export const cards = [
 ['erosione_polare','Erosione Polare','blue',0,'base','monster','Scegli un Mostro. Quando una carta gli fa perdere POW in questo turno, lo uccidi.'],
 ['vincolo_di_brina','Vincolo di Brina','blue',0,'base','tapEnemy','Come costo aggiuntivo, tappa un tuo Campione. Riduci di 2 il POW di un nemico fino alla fine del turno.'],
 ['esazione_delle_anime','Esazione delle Anime','black',2,'base','enemySoul','L’avversario perde 1 anima di un colore a tua scelta.'],
 ['richiamo_sepolcrale','Richiamo Sepolcrale','black',2,'base','graveMonster','Evoca 1 Mostro dal tuo Cimitero.'],
 ['rinascita','Rinascita','black',1,'instant','ownMonster','Scegli un tuo Mostro e forniscigli Lascito: ritorna in vita e perde questo Lascito. Non attiva gli effetti di entrata in gioco.'],
 ['marea_necrotica','Marea Necrotica','black',1,'base','none','Infliggi 1 danno a tutti i Mostri e cura di 1 danno tutti i tuoi Campioni.'],
 ['corazza_dei_caduti','Corazza dei Caduti','black',1,'response','own','Scegli un tuo Campione. Ogni volta che muore un Mostro in questo turno, ottiene 2 Armatura fino alla fine del turno.'],
 ['mandato_di_morte','Mandato di Morte','black',1,'response','monster','Uccidi un Mostro.'],
 ['sifone_d_anime','Sifone d’Anime','black',1,'response','damageHeal','Infliggi 1 danno a un nemico e cura di 2 danni un tuo Campione.'],
 ['lascito_profanato','Lascito Profanato','black',0,'base','lascitoMonster','Attiva il Lascito di un Mostro in gioco con 2 POW o meno, senza ucciderlo.'],
 ['risveglio_selvaggio','Risveglio Selvaggio','green',3,'base','none','Attiva tutti i tuoi Campioni.'],
 ['guardiano_delle_radici','Guardiano delle Radici','green',2,'base','monster','Scegli un Mostro. Ottiene +4 POW e Provocazione fino alla fine del turno.'],
 ['richiamo_del_branco_verde','Richiamo del Branco','green',0,'instant','any','Scegli un bersaglio. Non può ottenere Provocazione in questo turno. Se ha Provocazione, rimuovila fino alla fine del turno.'],
 ['spaccacorazze_della_giungla','Spaccacorazze della Giungla','green',0,'response','monster','Infliggi 1 danno a un Mostro; se ha Armatura, infliggine 3 invece.'],
 ['tutto_per_la_vittoria','Tutto per la Vittoria','red',2,'response','chargeDiscard','Come costo aggiuntivo, scarta 1 carta dalla tua mano. Un tuo Campione ottiene Carica 6 fino alla fine del turno.'],
 ['doppio_colpo','Doppio Colpo','red',2,'base','twoEnemies','Infliggi 2 danni a due nemici diversi.'],
 ['grido_di_guerra','Grido di Guerra','red',1,'base','none','Fornisci Carica 2 a tutti i tuoi Campioni fino alla fine del turno.'],
 ['ritorsione_cremisi','Ritorsione Cremisi','red',1,'base','monster','Quando viene scartata, puoi giocarla pagando il suo costo. Infliggi 4 danni a un Mostro.'],
 ['sangue_bollente','Sangue Bollente','red',0,'response','own','Un tuo Campione ottiene Carica 1 fino alla fine del turno.'],
 ['carica_incendiaria','Carica Incendiaria','red',1,'response','own','Un tuo Campione ottiene Carica 3 fino alla fine del turno.'],
].map(([id,name,color,cost,speed,target,text])=>({id,name,color,cost,speed,target,text,type:'Magia',effect:'batch3_'+id,art:id.replaceAll('_','-')+'.webp'}));
