const urls=[
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p01.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p02.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p03.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p04.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p05.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p06.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p07.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p08.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p09.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p10.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p11.txt',
'https://raw.githubusercontent.com/andreaamiraglia-svg/fanta-riftbound/main/soulforge/game-v22.p12.txt'];
const chunks=await Promise.all(urls.map(async u=>{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('Game chunk HTTP '+r.status);return r.text()}));
let source=chunks.join('');
const patch=(pattern:RegExp|string,replacement:string,label:string)=>{const next=source.replace(pattern as any,replacement);if(next===source)throw new Error('Game patch missing: '+label);source=next};

patch("const q = pl(s, p); if (!q || !COLORS.includes(color))\n    return; const before = q.souls[color] || 0;","const q = pl(s, p); if (!q || !COLORS.includes(color))\n    return; const allowedColors = Array.isArray(q.deckColors) && q.deckColors.length ? q.deckColors : (q.champions || []).map(c => c?.color).filter(Boolean); if (!allowedColors.includes(color))\n    return; const before = q.souls[color] || 0;",'soul colors');
patch("q.souls[color] = Math.min(3, before + n);","q.souls[color] = before + n;",'uncapped soul gain');
patch("function recordLyrandel(s, p, uid0, n, allow = true) { if (!allow || n !== 1 || (p !== 1 && p !== 2))","function recordLyrandel(s, p, uid0, n, allow = true) { if (!allow || n <= 0 || (p !== 1 && p !== 2))",'Lyrandel damage trigger');
patch("cervo_antico: { id: 'cervo_antico', name: 'Cervo Antico', color: 'green', pow: 3, text: 'Quando un Mostro subisce 1 danno, ottiene +1 POW per questo turno.' },","cervo_antico: { id: 'cervo_antico', name: 'Cervo Antico', color: 'green', pow: 3, text: 'Quando un altro Mostro subisce danni, quel Mostro ottiene +1 POW per questo turno.' },",'Cervo Antico text');
patch(/function applyMonsterDamage\(s, m, n\) \{[\s\S]*?\}\nexport function damageMonster\(s, p, uid0, n, source = '', allowLyrandel = true\) \{[\s\S]*?\}\nfunction reduceChampionPow/,`function applyMonsterDamage(s, m, n) { if (!m || n <= 0)
    return false; m.damage += n; log(s, \`${MONSTER_DEFS[m.cardId]?.name || m.cardId} subisce ${n} dann${n === 1 ? 'o' : 'i'} (${m.damage}/${currentMonsterPow(s, m)}).\`); return m.damage >= currentMonsterPow(s, m); }
export function damageMonster(s, p, uid0, n, source = '', allowLyrandel = true) { const m = monster(s, uid0); if (!m || n <= 0)
    return { died: false }; n = absorbArmor(s, m, n, MONSTER_DEFS[m.cardId]?.name || m.cardId); if (n <= 0)
    return { died: false }; recordLyrandel(s, p, uid0, n, allowLyrandel); const cervi = s.board.monsters.filter((x) => x.cardId === 'cervo_antico' && x.uid !== uid0).map((x) => ({ uid: x.uid, owner: x.owner })); if (applyMonsterDamage(s, m, n)) {
    killMonster(s, p, m, source, true);
    return { died: true };
} if (monster(s, uid0)) {
    for (const cervo of cervi) {
        s.triggerQueue.push({ actor: cervo.owner, sourceCardId: 'cervo_antico', effectId: 'cervo_antico_pow', effectName: 'Effetto — Cervo Antico', meta: { sourceUid: cervo.uid, targetUid: uid0 } });
        log(s, 'Cervo Antico attiva il suo effetto: entra in Catena.');
    }
} return { died: false }; }
function reduceChampionPow`,'Cervo Antico damage trigger');
patch(/function queueMonsterTrigger\(s, m, effectId, effectName, meta = \{\}\) \{[\s\S]*?\}\nfunction processMonsterEnter/,`function queueMonsterTrigger(s, m, effectId, effectName, meta = {}, choiceType = null) { const tr = { actor: m.owner, sourceCardId: m.cardId, effectId, effectName, meta }; if (choiceType) tr.choiceType = choiceType; s.triggerQueue.push(tr); log(s, \`${MONSTER_DEFS[m.cardId].name} attiva il suo effetto: entra in Catena.\`); }
function processMonsterEnter`,'queue monster trigger');
patch(/function processMonsterEnter\(s, m\) \{[\s\S]*?\}\nfunction processEnterQueue/,`function processMonsterEnter(s, m) { if (!m || !monster(s, m.uid)) return;
if (m.cardId === 'segugio_infernale') { const i = s.board.monsters.findIndex((x) => x.uid === m.uid); const uids = [s.board.monsters[i - 1]?.uid, s.board.monsters[i + 1]?.uid].filter(Boolean); queueMonsterTrigger(s, m, 'enter_segugio_infernale', 'Effetto — Segugio Infernale', { uids }); }
else if (m.cardId === 'drago_delle_ceneri') queueMonsterTrigger(s, m, 'enter_drago_ceneri', 'Effetto — Drago delle Ceneri', { sourceUid: m.uid });
else if (m.cardId === 'golem_magmatico') queueMonsterTrigger(s, m, 'enter_golem_magmatico', 'Effetto — Golem Magmatico');
else if (m.cardId === 'cerbero') queueMonsterTrigger(s, m, 'enter_cerbero', 'Effetto — Cerbero', {}, 'graveMonsterPow2');
else if (m.cardId === 'divoratore_di_anime_mostro') { const i = s.board.monsters.findIndex((x) => x.uid === m.uid); const uids = [s.board.monsters[i - 1]?.uid, s.board.monsters[i + 1]?.uid].filter(Boolean); queueMonsterTrigger(s, m, 'enter_divoratore_anime', 'Effetto — Divoratore di Anime', { sourceUid: m.uid, uids }); }
else if (m.cardId === 'squalo_delle_maree') queueMonsterTrigger(s, m, 'squalo_armor', 'Effetto — Squalo delle Maree');
else if (m.cardId === 'yeti') queueMonsterTrigger(s, m, 'yeti_freeze', 'Effetto — Yeti'); }
function processEnterQueue`,'monster enter effects');
patch(/function effectChoices\(s, tr\) \{[\s\S]*?\}\nfunction pushEffect/,`function effectChoices(s, tr) { if (tr.choiceType === 'enemyChampion') return pl(s, other(tr.actor)).champions.filter((c) => !c.defeated).map((c) => ({ id: c.id, label: c.name })); if (tr.choiceType === 'enemySoul') { const o = pl(s, other(tr.actor)); return COLORS.filter(c => (o.souls[c] || 0) > 0).map(c => ({ id: c, label: \`Anima ${colorLabel(c)}\` })); } if (tr.choiceType === 'monsterUids') return (tr.meta?.uids || []).filter((u) => !!monster(s, u)).map((u) => ({ id: u, label: MONSTER_DEFS[monster(s, u).cardId]?.name || u })); if (tr.choiceType === 'graveMonsterPow2') return [...new Set(pl(s, tr.actor).monsterGrave.filter((id) => MONSTER_DEFS[id]?.pow === 2))].map((id) => ({ id, label: MONSTER_DEFS[id]?.name || id })); return []; }
function pushEffect`,'trigger choices');
patch(/function pushEffect\(s, tr, choice\) \{[\s\S]*?\}\nfunction prepareTriggers/,`function pushEffect(s, tr, choice) { const targets = {}; if (tr.choiceType === 'enemyChampion') targets.champion = { player: other(tr.actor), champId: choice }; if (tr.choiceType === 'enemySoul') targets.color = choice; if (tr.choiceType === 'monsterUids') targets.monsterUid = choice; if (tr.choiceType === 'graveMonsterPow2') targets.graveMonsterId = choice; s.stack.push({ uid: uid(), kind: 'effect', actor: tr.actor, sourceCardId: tr.sourceCardId, effectId: tr.effectId, effectName: tr.effectName || 'Effetto', targets, meta: tr.meta || {} }); }
function prepareTriggers`,'push trigger effect');
patch("const id = String(a.choice || a.monsterUid || a.champId || a.color || '');","const id = String(a.choice || a.monsterUid || a.champId || a.color || a.graveMonsterId || '');",'trigger choice payload');
patch("meta || {}; log(s, `Si risolve ${item.effectName || 'un effetto'}.`); switch (item.effectId) {",`meta || {}; log(s, \`Si risolve ${item.effectName || 'un effetto'}.\`); switch (item.effectId) {
    case 'cervo_antico_pow': { const target = monster(s, m.targetUid); if (target) { target.tempPow = (target.tempPow || 0) + 1; log(s, \`${MONSTER_DEFS[target.cardId]?.name || target.cardId} ottiene +1 POW da Cervo Antico fino alla fine del turno.\`); } break; }
    case 'enter_segugio_infernale': beginDamageEvent(s, null); for (const u of m.uids || []) if (monster(s, u)) damageMonster(s, null, u, 1, 'Segugio Infernale', false); endDamageEvent(s); break;
    case 'enter_drago_ceneri': beginDamageEvent(s, null); for (const u of s.board.monsters.filter((x) => x.uid !== m.sourceUid).map((x) => x.uid)) if (monster(s, u)) damageMonster(s, null, u, 1, 'Drago delle Ceneri', false); endDamageEvent(s); break;
    case 'enter_golem_magmatico': for (const z of [1, 2]) for (const c of pl(s, z)?.champions || []) if (!c.defeated) damageChampion(s, z, c.id, 1, 'Golem Magmatico'); log(s, 'Golem Magmatico infligge 1 danno a tutti i Campioni.'); break;
    case 'enter_cerbero': { const id = String(t.graveMonsterId || ''); if (id && pl(s, p).monsterGrave.includes(id) && MONSTER_DEFS[id]?.pow === 2) reviveFromGrave(s, p, id); break; }
    case 'enter_divoratore_anime': { const src = monster(s, m.sourceUid); if (src) src.devouredColors = []; let killed = 0; for (const u of m.uids || []) { const victim = monster(s, u); if (!victim) continue; const color = MONSTER_DEFS[victim.cardId]?.color; killMonster(s, p, victim, 'Divoratore di Anime', false); if (src && color) src.devouredColors.push(color); killed++; } if (killed) log(s, \`Divoratore di Anime divora ${killed} Mostr${killed === 1 ? 'o' : 'i'}.\`); break; }`,'enter trigger resolution');
patch(/function provocationsAgainst\(s, p\) \{[\s\S]*?\}\nfunction validateAttackTarget/,`function provocationsAgainst(s, p) { const op = other(p); const ms = s.board.monsters.filter((m) => MONSTER_DEFS[m.cardId]?.provocazione).map((m) => ({ type: 'monster', uid: m.uid })); const cs = (pl(s, op)?.champions || []).filter((c) => !c.defeated && c.provocazione).map((c) => ({ type: 'champion', player: op, champId: c.id })); return [...ms, ...cs]; }
function validateAttackTarget`,'global provocation monsters');

patch("berserk: { id: 'berserk', name: 'Berserk', color: 'red', cost: 2, speed: 'instant', type: 'Magia', text: 'Attiva un tuo Campione danneggiato e forniscigli +2 POW.', effect: 'berserk' },","berserk: { id: 'berserk', name: 'Berserk', color: 'red', cost: 2, speed: 'instant', type: 'Magia', text: 'Attiva un tuo Campione danneggiato e forniscigli +2 POW.', effect: 'berserk' },\n    colpo_in_testa: { id: 'colpo_in_testa', name: 'Colpo in Testa', color: 'red', cost: 3, speed: 'base', type: 'Magia', text: 'Infliggi 5 danni a un Nemico. Se è un Campione e perde 1 HP, i danni in eccesso vengono inflitti dopo la pulizia dei danni.', effect: 'colpo_in_testa' },",'Colpo in Testa definition');
patch("mille_lame: { id: 'mille_lame', name: 'Tecnica delle Mille Lame Ninjitsu', color: 'green', cost: 12, speed: 'instant', type: 'Magia', text: 'Costa 1 Anima Verde in meno per ogni Mostro nel tuo Cimitero. Un tuo Campione ottiene +4 POW fino alla fine del turno.', effect: 'mille' },","mille_lame: { id: 'mille_lame', name: 'Tecnica delle Mille Lame Ninjitsu', color: 'green', cost: 12, speed: 'instant', type: 'Magia', text: 'Costa 1 Anima Verde in meno per ogni Mostro nel tuo Cimitero. Un tuo Campione ottiene +4 POW fino alla fine del turno.', effect: 'mille' },\n    fabbro_ninjitsu: { id: 'fabbro_ninjitsu', name: 'Fabbro Ninjitsu', color: 'green', cost: 1, speed: 'base', type: 'Magia', text: 'Un tuo Campione ottiene +2 POW fino alla fine del turno. Cerca una carta Ninjitsu nel tuo Mazzo e aggiungila alla tua mano.', effect: 'fabbro_ninjitsu' },",'Fabbro Ninjitsu definition');
patch("fino_alla_morte: { id: 'fino_alla_morte', name: 'Fino alla Morte', color: 'black', cost: 1, speed: 'instant', type: 'Magia', text: 'Scegli un tuo Campione. Bandisci tutti i Mostri dal tuo Cimitero. Quel Campione ottiene +1 POW per ogni Mostro bandito in questo modo fino alla fine del turno. Non può attaccare fino alla fine del turno.', effect: 'fino_alla_morte' },","fino_alla_morte: { id: 'fino_alla_morte', name: 'Fino alla Morte', color: 'black', cost: 1, speed: 'instant', type: 'Magia', text: 'Scegli un tuo Campione. Bandisci tutti i Mostri dal tuo Cimitero. Quel Campione ottiene +1 Armatura per ogni Mostro bandito in questo modo fino alla fine del turno.', effect: 'fino_alla_morte' },\n    richiamo_del_branco: { id: 'richiamo_del_branco', name: 'Richiamo del Branco', color: 'black', cost: 2, speed: 'base', type: 'Magia', text: 'Fino alla fine del turno, tutti i Mostri in campo ottengono: Lascito — Infliggi 1 danno a un Campione nemico.', effect: 'richiamo_del_branco' },",'Fino alla Morte and Richiamo definitions');
patch("flusso_gelido: { id: 'flusso_gelido', name: 'Flusso Gelido', color: 'blue', cost: 0, speed: 'instant', type: 'Magia', text: 'Riduce di 2 il POW di un Mostro per questo turno.', effect: 'flusso_gelido' },","grandine_brillante: { id: 'grandine_brillante', name: 'Grandine Brillante', color: 'blue', cost: 1, speed: 'base', type: 'Magia', text: 'Riduce di 1 il POW di tutti i nemici.', effect: 'grandine_brillante' },\n    flusso_gelido: { id: 'flusso_gelido', name: 'Flusso Gelido', color: 'blue', cost: 0, speed: 'instant', type: 'Magia', text: 'Riduce di 2 il POW di un Mostro per questo turno.', effect: 'flusso_gelido' },",'Grandine Brillante definition');

patch("function addArmorChampion(s, p, id, n, source = '') {",`function damageChampionOverflow(s, p, id, n, source = '') { const c = champ(s, p, id); if (!c || c.defeated || n <= 0) return { wounded: false, wounds: 0 }; n = absorbArmor(s, c, n, c.name); if (n <= 0) return { wounded: false, wounds: 0 }; let remaining = n, wounds = 0; while (remaining > 0 && !c.defeated) { const threshold = Math.max(1, currentPow(s, p, c)); const needed = Math.max(1, threshold - (c.damage || 0)); const dealt = Math.min(remaining, needed); c.damage += dealt; remaining -= dealt; log(s, \`${c.name} subisce ${dealt} dann${dealt === 1 ? 'o' : 'i'} (${c.damage}/${threshold}).\`); if (c.damage >= threshold) { woundChampion(s, p, c, source); wounds++; } else break; } return { wounded: wounds > 0, wounds }; }
function addArmorChampion(s, p, id, n, source = '') {`,'overflow champion damage helper');
patch("enqueueLascito(s, dead, killer, kings); }",`enqueueLascito(s, dead, killer, kings); if ((killer === 1 || killer === 2) && Number(dead.richiamoBrancoTurn) === Number(s.turn)) { const count = 1 + kings; for (let i = 0; i < count; i++) s.triggerQueue.push({ actor: killer, sourceCardId: 'richiamo_del_branco', effectId: 'lascito_richiamo_branco', choiceType: 'enemyChampion', effectName: 'Lascito — Richiamo del Branco' }); log(s, \`Richiamo del Branco: Lascito viene ottenuto da ${pl(s, killer).name} ed entra in Catena${count > 1 ? ` (${count} attivazioni)` : ''}.\`); } }`,'Richiamo temporary Lascito');
patch(/case 'fino_alla_morte': \{[\s\S]*?break;\n        \}/,`case 'fino_alla_morte': { const n = q.monsterGrave.length; q.banishedMonsters.push(...q.monsterGrave); q.monsterGrave = []; const x = champ(s, p, t.ownChamp); if (x && !x.defeated && n > 0) addArmorChampion(s, p, x.id, n, c.name); log(s, \`${q.name} bandisce ${n} Mostr${n === 1 ? 'o' : 'i'} dal Cimitero.\`); break; }`,'Fino alla Morte resolution');
patch("case 'berserk': {",`case 'colpo_in_testa': { const d = spellDamage(s, p, 5); if (t.enemy?.type === 'champion') damageChampionOverflow(s, t.enemy.player, t.enemy.champId, d, c.name); else if (t.enemy?.type === 'monster') { beginDamageEvent(s, p); damageMonster(s, p, t.enemy.uid, d, c.name, true); endDamageEvent(s); } break; }
        case 'berserk': {`,'Colpo resolution');
patch("case 'taglio_ninjitsu':",`case 'fabbro_ninjitsu': { const x = champ(s, p, t.ownChamp); if (x && !x.defeated) { x.tempPow += 2; log(s, \`${x.name} ottiene +2 POW fino alla fine del turno da Fabbro Ninjitsu.\`); } const id = String(t.deckCardId || ''); const i = q.deck.indexOf(id); if (i >= 0 && CARD_DEFS[id] && String(CARD_DEFS[id].name || '').toLowerCase().includes('ninjitsu')) { q.deck.splice(i, 1); q.hand.push(id); log(s, \`${q.name} cerca ${CARD_DEFS[id].name} nel Mazzo e la aggiunge alla mano.\`); } break; }
        case 'taglio_ninjitsu':`,'Fabbro resolution');
patch("case 'evocatore_anime_vacue': {",`case 'richiamo_del_branco': { for (const mx of s.board.monsters) { mx.richiamoBrancoTurn = s.turn; const list = Array.isArray(mx.turnEffects) ? mx.turnEffects : []; list.push({ turn: s.turn, sourceCardId: 'richiamo_del_branco', kind: 'buff', label: 'Lascito — 1 danno a un Campione nemico' }); mx.turnEffects = list.filter((e) => Number(e?.turn) === Number(s.turn)).slice(-24); } log(s, 'Tutti i Mostri in campo ottengono il Lascito di Richiamo del Branco fino alla fine del turno.'); break; }
        case 'evocatore_anime_vacue': {`,'Richiamo resolution');
patch("case 'flusso_gelido': {",`case 'grandine_brillante': { const op = other(p); for (const x of pl(s, op).champions) if (!x.defeated) reduceChampionPow(s, op, x.id, 1, c.name); for (const mx of s.board.monsters) reduceMonsterPow(s, mx, 1, c.name); break; }
        case 'flusso_gelido': {`,'Grandine resolution');
patch("case 'lascito_segugio':",`case 'lascito_richiamo_branco': if (champ(s, t.champion?.player, t.champion?.champId)) damageChampion(s, t.champion.player, t.champion.champId, 1, 'Lascito — Richiamo del Branco'); break;
    case 'lascito_segugio':`,'Richiamo Lascito resolution');
patch("if (['corazza', 'mano', 'occhio', 'berserk', 'katana', 'albero', 'mille', 'collasso', 'fino_alla_morte'].includes(c.effect) && !own(String(t?.ownChamp || '')))","if (['corazza', 'mano', 'occhio', 'berserk', 'katana', 'albero', 'mille', 'collasso', 'fino_alla_morte', 'fabbro_ninjitsu'].includes(c.effect) && !own(String(t?.ownChamp || '')))",'Fabbro champion validation');
patch("if (['sfera', 'fendente', 'eclipse_fang', 'staffa_mare', 'custode_deboli'].includes(c.effect) && !validEnemyTarget(s, p, t?.enemy))","if (['sfera', 'fendente', 'eclipse_fang', 'staffa_mare', 'custode_deboli', 'colpo_in_testa'].includes(c.effect) && !validEnemyTarget(s, p, t?.enemy))",'Colpo target validation');
patch("if (c.effect === 'occhio' && pl(s, p).deck.length < 5)\n    throw new Error('Occhio di Drago richiede almeno 5 carte nel mazzo.'); }",`if (c.effect === 'occhio' && pl(s, p).deck.length < 5) throw new Error('Occhio di Drago richiede almeno 5 carte nel mazzo.'); if (c.effect === 'fabbro_ninjitsu') { const id = String(t?.deckCardId || ''); if (!pl(s, p).deck.includes(id) || !CARD_DEFS[id] || !String(CARD_DEFS[id].name || '').toLowerCase().includes('ninjitsu')) throw new Error('Fabbro Ninjitsu richiede una carta Ninjitsu presente nel tuo Mazzo.'); } }`,'Fabbro deck validation');
patch("for (const m of s.board.monsters) {\n    m.damage = 0;\n    m.tempPow = 0;\n    m.armor = 0;\n}","for (const m of s.board.monsters) {\n    m.damage = 0;\n    m.tempPow = 0;\n    m.armor = 0;\n    delete m.richiamoBrancoTurn;\n}",'Richiamo cleanup');

const mod=await import('data:text/javascript;charset=utf-8,'+encodeURIComponent(source));
const COLORS=['red','green','black','blue'];
function enforceSoulColorsOnPlayer(q:any){ if(!q)return q; const allowed=new Set(Array.isArray(q.deckColors)&&q.deckColors.length?q.deckColors:(q.champions||[]).map((c:any)=>c?.color).filter(Boolean)); q.souls ||= {}; for(const c of COLORS){ const n=Math.max(0,Number(q.souls[c]||0)); q.souls[c]=allowed.has(c)?n:0; } return q; }
function enforceSoulColors(state:any){ if(!state?.players)return state; enforceSoulColorsOnPlayer(state.players['1']); enforceSoulColorsOnPlayer(state.players['2']); return state; }
type Snap={tempPow:number;powMod:number;armor:number;cantAttackTurn:any;tapped:boolean;cardId?:string};
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:0;} function keyChamp(p:number,id:string){return `c:${p}:${id}`;} function keyMonster(uid:string){return `m:${uid}`;}
function capture(state:any){const out=new Map<string,Snap>();for(const p of [1,2])for(const c of state?.players?.[String(p)]?.champions||[])out.set(keyChamp(p,String(c.id)),{tempPow:num(c.tempPow),powMod:0,armor:num(c.armor),cantAttackTurn:c.cantAttackTurn??null,tapped:!!c.tapped,cardId:String(c.id)});for(const m of state?.board?.monsters||[])out.set(keyMonster(String(m.uid)),{tempPow:num(m.tempPow),powMod:num(m.powMod),armor:num(m.armor),cantAttackTurn:null,tapped:false,cardId:String(m.cardId)});return out;}
function sourceFromState(state:any,move:any){const type=String(move?.type||'');if(type==='pass_priority'){const top=state?.stack?.[state.stack.length-1];if(top)return String(top.cardId||top.sourceCardId||'')||null;}if(type==='cast'&&move?.cardId)return String(move.cardId);if(type==='activate_champion'&&move?.champId)return String(move.champId);return null;}
function addTurnEffect(target:any,turn:number,sourceCardId:string|null,kind:'buff'|'debuff'|'status',label:string){if(!target||!sourceCardId||!label)return;const list=Array.isArray(target.turnEffects)?target.turnEffects:[];list.push({turn,sourceCardId,kind,label});target.turnEffects=list.filter((x:any)=>Number(x?.turn)===Number(turn)).slice(-24);}
function clearTurnEffects(state:any){for(const p of [1,2])for(const c of state?.players?.[String(p)]?.champions||[])c.turnEffects=[];for(const m of state?.board?.monsters||[])m.turnEffects=[];}
function recordDiff(before:Map<string,Snap>,after:any,sourceCardId:string|null,turn:number){for(const p of [1,2])for(const c of after?.players?.[String(p)]?.champions||[]){const b=before.get(keyChamp(p,String(c.id)));if(!b)continue;const powDelta=num(c.tempPow)-b.tempPow;if(powDelta!==0)addTurnEffect(c,turn,sourceCardId,powDelta>0?'buff':'debuff',`POW ${powDelta>0?'+':''}${powDelta}`);const armorDelta=num(c.armor)-b.armor;if(armorDelta>0)addTurnEffect(c,turn,sourceCardId,'buff',`Armatura +${armorDelta}`);if((c.cantAttackTurn??null)!==b.cantAttackTurn&&Number(c.cantAttackTurn)===Number(turn))addTurnEffect(c,turn,sourceCardId,'debuff','Non può attaccare');if(b.tapped&&!c.tapped&&sourceCardId)addTurnEffect(c,turn,sourceCardId,'status','Riattivato');}for(const m of after?.board?.monsters||[]){const b=before.get(keyMonster(String(m.uid)));if(!b)continue;const powDelta=(num(m.tempPow)-b.tempPow)+(num(m.powMod)-b.powMod);let powSource=sourceCardId;if(String(m.cardId)==='orso_furioso'&&powDelta>0)powSource='orso_furioso';if(powDelta!==0)addTurnEffect(m,turn,powSource,powDelta>0?'buff':'debuff',`POW ${powDelta>0?'+':''}${powDelta}`);const armorDelta=num(m.armor)-b.armor;if(armorDelta>0)addTurnEffect(m,turn,sourceCardId,'buff',`Armatura +${armorDelta}`);}}
export const CARD_DEFS=mod.CARD_DEFS;export const MONSTER_DEFS=mod.MONSTER_DEFS;export const CHAMPION_DEFS=mod.CHAMPION_DEFS;export const DECK_RULES=mod.DECK_RULES;export const STARTER_DECK=mod.STARTER_DECK;export const STARTER_MONSTERS=mod.STARTER_MONSTERS;export const newState=(name:any,deckConfig:any)=>enforceSoulColors(mod.newState(name,deckConfig));export const newPlayer=(name:any,deckConfig:any)=>enforceSoulColorsOnPlayer(mod.newPlayer(name,deckConfig));
export function act(state:any,p:any,move:any){enforceSoulColors(state);const turnBefore=Number(state?.turn||0),snap=capture(state),src=sourceFromState(state,move);const next=enforceSoulColors(mod.act(state,p,move));const turnAfter=Number(next?.turn||0);if(turnAfter!==turnBefore)clearTurnEffects(next);else recordDiff(snap,next,src,turnAfter);return next;}
export const publicView=(state:any,p:any)=>mod.publicView(enforceSoulColors(state),p);
