import * as base from './game-v40-loader.ts';

export const CARD_DEFS:any=base.CARD_DEFS;
export const MONSTER_DEFS:any=base.MONSTER_DEFS;
export const CHAMPION_DEFS:any=base.CHAMPION_DEFS;
export const DECK_RULES=base.DECK_RULES;
export const newState=base.newState;
export const newPlayer=base.newPlayer;
export const publicView=base.publicView;

const ORANGE='orange';
const ALL_COLORS=['red','green','black','blue','orange'];
const CUSTOM_CARD_IDS=new Set(['frecce_divine','parry','perfezione','pugno_in_faccia','su_gli_scudi']);
const uid=()=>crypto.randomUUID();
const clone=(x:any)=>JSON.parse(JSON.stringify(x));
const other=(p:number)=>p===1?2:1;
const player=(s:any,p:number)=>s?.players?.[String(p)]||null;
const champ=(s:any,p:number,id:string)=>(player(s,p)?.champions||[]).find((c:any)=>String(c?.id)===String(id));
const monster=(s:any,id:string)=>(s?.board?.monsters||[]).find((m:any)=>String(m?.uid)===String(id));
const support=(s:any,p:number,id:string)=>(player(s,p)?.champions||[]).find((c:any)=>c?.supportChampion&&String(c?.id)===String(id));
const isStarterChamp=(c:any)=>!!c&&!c.supportChampion;
const log=(s:any,msg:string)=>{s.log ||= [];s.log.push(msg);if(s.log.length>180)s.log=s.log.slice(-180)};
const colorLabel=(c:string)=>c==='red'?'Rossa':c==='green'?'Verde':c==='black'?'Nera':c==='blue'?'Blu':'Arancione';

CHAMPION_DEFS.kroth={id:'kroth',name:'Kroth il Fulminatore',color:ORANGE,basePow:3,hp:3};
if(CARD_DEFS.alabardo)Object.assign(CARD_DEFS.alabardo,{color:ORANGE,type:'Supporto',subtype:undefined,supportChampion:true,speed:'base',cost:1,text:'Quando entra in gioco, fornisce Provocazione a un altro tuo Campione per questo turno.'});
if(CHAMPION_DEFS.alabardo)Object.assign(CHAMPION_DEFS.alabardo,{color:ORANGE,basePow:1,hp:1,supportChampion:true});
if(CARD_DEFS.spacca_teste)Object.assign(CARD_DEFS.spacca_teste,{color:ORANGE,cost:1,speed:'response',type:'Magia',text:'Risposta. Fornisci Contrattacco a un tuo Campione fino alla fine del turno.'});

Object.assign(CARD_DEFS,{
 frecce_divine:{id:'frecce_divine',name:'Frecce Divine',color:ORANGE,cost:0,speed:'base',type:'Magia',text:'Infliggi 1 danno a un Mostro per ogni Supporto che controlli.',effect:'frecce_divine'},
 legionario_troll:{id:'legionario_troll',name:'Legionario Troll',color:ORANGE,cost:3,speed:'base',type:'Supporto',supportChampion:true,text:'Quando attacca, fornisce +2 POW e Provocazione a un tuo Campione per questo turno.',effect:'support_legionario_troll'},
 loda_il_sole:{id:'loda_il_sole',name:'Loda il Sole',color:ORANGE,cost:0,speed:'base',type:'Supporto',supportChampion:true,text:'Muore alla fine del turno.',effect:'support_loda_il_sole'},
 parry:{id:'parry',name:'Parry',color:ORANGE,cost:2,speed:'response',type:'Magia',text:'Risposta. Scegli un tuo Campione in difesa. Quel Campione diventa l’attaccante.',effect:'parry'},
 perfezione:{id:'perfezione',name:'Perfezione',color:ORANGE,cost:1,speed:'instant',type:'Magia',text:'Istantanea. Tutti i tuoi Campioni ottengono +1 POW per questo turno.',effect:'perfezione'},
 pugno_in_faccia:{id:'pugno_in_faccia',name:'Pugno in Faccia',color:ORANGE,cost:0,speed:'base',type:'Magia',text:'Un tuo Supporto attacca.',effect:'pugno_in_faccia'},
 soldato_corrotto:{id:'soldato_corrotto',name:'Soldato Corrotto',color:ORANGE,cost:2,speed:'base',type:'Supporto',supportChampion:true,text:'I tuoi Campioni e Mostri con Provocazione ottengono +2 POW.',effect:'support_soldato_corrotto'},
 su_gli_scudi:{id:'su_gli_scudi',name:'Su gli Scudi',color:ORANGE,cost:1,speed:'response',type:'Magia',text:'Risposta. Un tuo Campione in difesa ottiene +4 Armatura fino alla fine di quel combattimento.',effect:'su_gli_scudi'}
});
Object.assign(CHAMPION_DEFS,{
 legionario_troll:{id:'legionario_troll',name:'Legionario Troll',color:ORANGE,basePow:3,hp:1,supportChampion:true},
 loda_il_sole:{id:'loda_il_sole',name:'Loda il Sole',color:ORANGE,basePow:0,hp:1,supportChampion:true},
 soldato_corrotto:{id:'soldato_corrotto',name:'Soldato Corrotto',color:ORANGE,basePow:2,hp:1,supportChampion:true},
 sciamano_del_sole_support:{id:'sciamano_del_sole_support',name:'Sciamano del Sole',color:ORANGE,basePow:1,hp:1,supportChampion:true,tokenSupport:true}
});
CARD_DEFS.sciamano_del_sole_support={id:'sciamano_del_sole_support',name:'Sciamano del Sole',color:ORANGE,cost:0,speed:'base',type:'Supporto',supportChampion:true,tokenSupport:true,text:'Forma Supporto evocata da Lascito.',effect:'support_sciamano_token'};
Object.assign(MONSTER_DEFS,{
 falco_dell_alba:{id:'falco_dell_alba',name:'Falco dell’Alba',color:ORANGE,pow:3,text:'Quando entra in gioco, tutti i Campioni ottengono +1 POW.'},
 golem_d_ambra:{id:'golem_d_ambra',name:'Golem d’Ambra',color:ORANGE,pow:2,text:'Quando entra in gioco, ottiene 3 Armatura.'},
 grifone_imperiale:{id:'grifone_imperiale',name:'Grifone Imperiale',color:ORANGE,pow:3,text:'Tutti i Mostri e i Campioni con Provocazione ottengono +1 POW.'},
 leone_solare:{id:'leone_solare',name:'Leone Solare',color:ORANGE,pow:3,text:'Contrattacco — Infligge danni in Combattimento anche quando è il difensore.',counterattack:true},
 sciamano_del_sole:{id:'sciamano_del_sole',name:'Sciamano del Sole',color:ORANGE,pow:1,text:'Lascito — Evoca Sciamano del Sole sotto il tuo controllo come Supporto con 1 POW.',lascito:'sciamano'},
 drago_aureo:{id:'drago_aureo',name:'Drago Aureo',color:ORANGE,pow:3,text:'Tutte le carte Supporto hanno Provocazione.'}
});
export const STARTER_DECK=Object.keys(CARD_DEFS).filter(id=>!CARD_DEFS[id]?.tokenSupport);
export const STARTER_MONSTERS=Object.keys(MONSTER_DEFS);

function championPow(s:any,p:number,c:any){let v=Number(c?.basePow||0)+Number(c?.tempPow||0);if(c?.id==='kael'&&(player(s,p)?.hand?.length||0)===0&&s?.status==='main')v+=3;return Math.max(0,v)}
function monsterPow(s:any,m:any){const d=MONSTER_DEFS[m?.cardId];if(!d)return 0;let v=Number(d.pow||0)+Number(m?.powMod||0)+Number(m?.tempPow||0);v+=(s?.board?.monsters||[]).filter((x:any)=>x.cardId==='lupo_delle_radici'&&x.uid!==m.uid).length;const ice=(s?.board?.monsters||[]).filter((x:any)=>x.cardId==='lupo_glaciale'&&x.uid!==m.uid).length;const storms=(s?.board?.monsters||[]).filter((x:any)=>x.cardId==='grifone_della_tempesta').length;if(ice)v-=ice*(1+storms);return Math.max(0,v)}
function gainSoul(s:any,p:number,color:string,n=1){const q=player(s,p);if(!q||!ALL_COLORS.includes(color))return;q.souls ||= {};q.souls[color]=Number(q.souls[color]||0);const before=q.souls[color];q.souls[color]=Math.min(3,before+n);const got=q.souls[color]-before;if(got>0)log(s,`${q.name} recupera ${got} Anima${got===1?'':'e'} ${got===1?colorLabel(color):(color==='orange'?'Arancioni':colorLabel(color))}.`)}
function checkWinner(s:any){if(s?.status==='gameover')return;for(const p of [1,2]){const starters=(player(s,p)?.champions||[]).filter(isStarterChamp);if(starters.length&&starters.every((c:any)=>c.defeated)){s.status='gameover';s.winner=other(p);log(s,`${player(s,other(p))?.name||`Giocatore ${other(p)}`} vince la partita!`);return}}}
function woundChampionLocal(s:any,p:number,c:any,source=''){if(!c||c.defeated)return;c.wounds=Number(c.wounds||0)+1;c.damage=0;log(s,`${c.name} subisce una Ferita (${c.wounds}/${c.hp})${source?` da ${source}`:''}.`);if(c.wounds>=Number(c.hp||1)){c.defeated=true;c.tapped=true;log(s,`${c.name} è sconfitto.`);checkWinner(s)}}
function damageChampionLocal(s:any,p:number,id:string,n:number,source=''){const c=champ(s,p,id);if(!c||c.defeated||n<=0)return;const a=Math.max(0,Number(c.armor||0)),blocked=Math.min(a,n);if(blocked){c.armor=a-blocked;log(s,`${c.name} usa ${blocked} Armatura e annulla ${blocked} dann${blocked===1?'o':'i'}.`)}n-=blocked;if(n<=0)return;c.damage=Number(c.damage||0)+n;const th=Math.max(1,championPow(s,p,c));log(s,`${c.name} subisce ${n} dann${n===1?'o':'i'} (${c.damage}/${th}).`);if(c.damage>=th)woundChampionLocal(s,p,c,source)}
function cleanupSupportDeaths(s:any){for(const p of [1,2]){const q=player(s,p);if(!q)continue;const keep=[];for(const c of q.champions||[]){if(c?.supportChampion&&c.defeated){q.grave ||= [];q.grave.push(String(c.sourceCardId||c.id));log(s,`${c.name} viene messo nel Cimitero di ${q.name}.`)}else keep.push(c)}q.champions=keep}}
function freshSupport(id:string,sourceCardId=id){const d=CHAMPION_DEFS[id];return {...d,wounds:0,damage:0,tempPow:0,armor:0,tapped:false,defeated:false,cantAttackTurn:null,supportChampion:true,sourceCardId,turnEffects:[]}}
function summonSciamanoSupport(s:any,p:number){const q=player(s,p);if(!q)return;const c=freshSupport('sciamano_del_sole_support','sciamano_del_sole_support');c.tokenSupport=true;q.champions.push(c);log(s,`Sciamano del Sole viene evocato sotto il controllo di ${q.name} come Supporto con 1 POW.`)}
function localLascitoDescriptor(m:any,killer:number){const d=MONSTER_DEFS[m.cardId];if(!d?.lascito)return null;if(d.lascito==='segugio_morti')return{actor:killer,sourceCardId:m.cardId,effectId:'lascito_segugio',choiceType:'enemyChampion',effectName:`Lascito — ${d.name}`};if(d.lascito==='custode')return{actor:killer,sourceCardId:m.cardId,effectId:'lascito_custode',effectName:`Lascito — ${d.name}`};if(d.lascito==='cavaliere')return{actor:killer,sourceCardId:m.cardId,effectId:'lascito_cavaliere',choiceType:'enemyChampion',effectName:`Lascito — ${d.name}`};if(d.lascito==='serpente')return{actor:killer,sourceCardId:m.cardId,effectId:'lascito_serpente',choiceType:'enemySoul',effectName:`Lascito — ${d.name}`};if(d.lascito==='divoratore')return{actor:killer,sourceCardId:m.cardId,effectId:'lascito_divoratore',meta:{colors:[...(m.devouredColors||[])]},effectName:`Lascito — ${d.name}`};if(d.lascito==='sciamano')return{actor:killer,sourceCardId:m.cardId,effectId:'lascito_sciamano',effectName:`Lascito — ${d.name}`};return null}
function queueOrangeTrigger(s:any,tr:any){s._orangeTriggers ||= [];s._orangeTriggers.push(tr)}
function triggerOptions(s:any,tr:any){if(tr.choiceType==='enemyChampion')return(player(s,other(tr.actor))?.champions||[]).filter((c:any)=>!c.defeated&&isStarterChamp(c)).map((c:any)=>({id:String(c.id),label:c.name}));if(tr.choiceType==='enemySoul'){const o=player(s,other(tr.actor));return ALL_COLORS.filter(c=>Number(o?.souls?.[c]||0)>0).map(c=>({id:c,label:`Anima ${colorLabel(c)}`}))}if(tr.choiceType==='ownChampion')return(player(s,tr.actor)?.champions||[]).filter((c:any)=>!c.defeated&&isStarterChamp(c)).map((c:any)=>({id:String(c.id),label:c.name}));if(tr.choiceType==='monsterUids')return(tr.meta?.uids||[]).filter((u:string)=>!!monster(s,u)).map((u:string)=>({id:u,label:MONSTER_DEFS[monster(s,u)?.cardId]?.name||u}));return[]}
function processOrangeTriggers(s:any){if(s?.pendingChoice)return;const q=s?._orangeTriggers;if(!Array.isArray(q)||!q.length)return;while(q.length&&!s.pendingChoice){const tr=q.shift();if(tr.choiceType){const opts=triggerOptions(s,tr);if(!opts.length){log(s,`${tr.effectName||'Effetto'} non ha bersagli validi.`);continue}s.pendingChoice={type:'trigger_target',player:tr.actor,trigger:tr,options:opts};s.priority=null;return}s.stack ||= [];s.stack.push({uid:uid(),kind:'effect',actor:tr.actor,sourceCardId:tr.sourceCardId,effectId:tr.effectId,effectName:tr.effectName||'Effetto',targets:{},meta:tr.meta||{}})}if(s.stack?.length){s.priority=other(Number(s.stack[s.stack.length-1].actor));s.priorityPasses=0}}
function enqueueLascito(s:any,dead:any,killer:number,kingCount:number){if(killer!==1&&killer!==2)return;const d=localLascitoDescriptor(dead,killer);if(!d)return;const count=1+kingCount;for(let i=0;i<count;i++)queueOrangeTrigger(s,clone(d));log(s,`${MONSTER_DEFS[dead.cardId]?.name}: Lascito viene ottenuto da ${player(s,killer)?.name}${count>1?` (${count} attivazioni)`:''}.`)}
function killMonsterLocal(s:any,killer:number,m:any,reason='',grant=true,kingOverride?:number){const i=(s?.board?.monsters||[]).findIndex((x:any)=>x.uid===m.uid);if(i<0)return;const kings=kingOverride??(s.board.monsters||[]).filter((x:any)=>x.cardId==='re_dei_non_morti').length;const dead=clone(m);s.board.monsters.splice(i,1);player(s,dead.owner)?.monsterGrave?.push(dead.cardId);log(s,`${MONSTER_DEFS[dead.cardId]?.name||dead.cardId} viene sconfitto${reason?` da ${reason}`:''}.`);if(killer===1||killer===2){const q=player(s,killer);q.killedMonsterThisTurn=true;if(grant)gainSoul(s,killer,MONSTER_DEFS[dead.cardId]?.color,1)}for(const b of s.board.monsters.filter((x:any)=>x.cardId==='orso_furioso')){b.tempPow=Number(b.tempPow||0)+2;log(s,'Orso Furioso ottiene +2 POW fino alla fine del turno.')}enqueueLascito(s,dead,killer,kings)}
function damageMonsterLocal(s:any,p:number,uid0:string,n:number,source=''){const m=monster(s,uid0);if(!m||n<=0)return;const a=Math.max(0,Number(m.armor||0)),blocked=Math.min(a,n);if(blocked){m.armor=a-blocked;log(s,`${MONSTER_DEFS[m.cardId]?.name||m.cardId} usa ${blocked} Armatura e annulla ${blocked} dann${blocked===1?'o':'i'}.`)}n-=blocked;if(n<=0)return;m.damage=Number(m.damage||0)+n;const th=Math.max(0,monsterPow(s,m));log(s,`${MONSTER_DEFS[m.cardId]?.name||m.cardId} subisce ${n} dann${n===1?'o':'i'} (${m.damage}/${th}).`);if(m.damage>=th){killMonsterLocal(s,p,m,source,true);return}const deer=s.board.monsters.filter((x:any)=>x.cardId==='cervo_antico'&&x.uid!==m.uid).length;if(deer){m.tempPow=Number(m.tempPow||0)+deer;log(s,`${MONSTER_DEFS[m.cardId]?.name||m.cardId} ottiene +${deer} POW dal Cervo Antico fino alla fine del turno.`)}const lyr=champ(s,p,'lyrandel'),q=player(s,p);if(p&&lyr&&!lyr.defeated&&!q.lyrandelUsed&&monster(s,uid0)){q.lyrandelUsed=true;queueOrangeTrigger(s,{actor:p,sourceCardId:'lyrandel',effectId:'lyrandel_bonus',choiceType:'monsterUids',meta:{uids:[uid0]},effectName:'Effetto di Lyrandel'})}}
function legalAttackTarget(s:any,p:number,t:any){const guards:any[]=[];for(const m of s.board.monsters||[])if(MONSTER_DEFS[m.cardId]?.provocazione||m.provocazione)guards.push({type:'monster',uid:m.uid});for(const c of player(s,other(p))?.champions||[])if(!c.defeated&&c.provocazione)guards.push({type:'champion',player:other(p),champId:c.id});const same=(a:any,b:any)=>a?.type===b?.type&&(a.type==='monster'?String(a.uid)===String(b.uid):(Number(a.player)===Number(b.player)&&String(a.champId)===String(b.champId)));if(guards.length)return guards.some(g=>same(g,t));if(t?.type==='monster')return !!monster(s,String(t.uid));if(t?.type==='champion')return Number(t.player)===other(p)&&!!champ(s,other(p),String(t.champId))&&!champ(s,other(p),String(t.champId)).defeated;return false}
function beginSupportAttack(s:any,p:number,supportId:string,target:any){if(s.priority||s.stack?.length||s.combat)throw new Error('Non puoi iniziare questo attacco durante una Catena o un altro combattimento.');const c=support(s,p,supportId);if(!c||c.defeated||c.tapped)throw new Error('Supporto non disponibile per attaccare.');if(!legalAttackTarget(s,p,target))throw new Error('Devi attaccare un difensore con Provocazione, se presente.');c.tapped=true;s.combat={initiator:p,attacker:{player:p,champId:c.id},target:clone(target),cancelled:false};s.combatPasses=0;s.stackInitiator=p;s.priority=other(p);s.mainPasses=0;log(s,`${c.name} attacca grazie a Pugno in Faccia.`);onCombatDeclared(s,p,c,target)}
function onCombatDeclared(s:any,p:number,attacker:any,target:any){if(target?.type==='champion'){const d=champ(s,Number(target.player),String(target.champId));if(d?.id==='kroth'&&!d.defeated&&isStarterChamp(d)){d.tempPow=Number(d.tempPow||0)+1;log(s,`${d.name} difende e ottiene +1 POW fino alla fine del turno.`)}}if(attacker?.id==='legionario_troll'&&attacker.supportChampion){queueOrangeTrigger(s,{actor:p,sourceCardId:'legionario_troll',effectId:'legionario_troll_attack',choiceType:'ownChampion',effectName:'Effetto — Legionario Troll'});processOrangeTriggers(s)}}
function resolveOrangeChoice(s:any,p:number,a:any){const pc=s?.pendingChoice;if(!pc||pc.type!=='trigger_target'||pc.trigger?.effectId!=='legionario_troll_attack')return false;if(Number(pc.player)!==p)throw new Error('C’è una scelta in attesa dell’altro giocatore.');const id=String(a.choice||a.champId||'');if(!pc.options?.some((x:any)=>String(x.id)===id))throw new Error('Campione bersaglio non valido.');s.pendingChoice=null;s.stack ||= [];s.stack.push({uid:uid(),kind:'effect',actor:p,sourceCardId:pc.trigger.sourceCardId,effectId:'legionario_troll_attack',effectName:pc.trigger.effectName,targets:{ownChamp:id},meta:{}});s.priority=other(p);s.priorityPasses=0;log(s,`${pc.trigger.effectName} entra in Catena.`);return true}
function combatKey(c:any){if(!c)return'';return`${c.attacker?.player}:${c.attacker?.champId}>${c.target?.type}:${c.target?.player||''}:${c.target?.champId||c.target?.uid||''}`}
function applyEffectResolution(s:any,item:any){const p=Number(item.actor),t=item.targets||{};switch(item.effectId){case'frecce_divine':{const count=(player(s,p)?.champions||[]).filter((c:any)=>c.supportChampion&&!c.defeated).length;const u=String(t.monsterUid||'');if(monster(s,u)&&count>0)damageMonsterLocal(s,p,u,count,'Frecce Divine');else log(s,`Frecce Divine infligge ${count} danni.`);break}case'parry':{const c=s.combat;if(!c)break;const id=String(t.ownChamp||'');const d=champ(s,p,id);if(!d||d.defeated||d.supportChampion||c.target?.type!=='champion'||Number(c.target.player)!==p||String(c.target.champId)!==id)break;const old=clone(c.attacker);c.attacker={player:p,champId:id};c.target={type:'champion',player:Number(old.player),champId:String(old.champId)};c.initiator=p;c.combatPasses=0;s.priority=other(p);s.stackInitiator=p;log(s,`${d.name} esegue Parry e diventa l’attaccante.`);break}case'perfezione':for(const c of player(s,p)?.champions||[])if(!c.defeated&&isStarterChamp(c))c.tempPow=Number(c.tempPow||0)+1;log(s,`Tutti i Campioni di ${player(s,p)?.name} ottengono +1 POW grazie a Perfezione.`);break;case'pugno_in_faccia':beginSupportAttack(s,p,String(t.supportId||''),t.target);break;case'su_gli_scudi':{const c=s.combat,id=String(t.ownChamp||'');const d=champ(s,p,id);if(!c||!d||d.defeated||d.supportChampion||c.target?.type!=='champion'||Number(c.target.player)!==p||String(c.target.champId)!==id)break;d.armor=Number(d.armor||0)+4;d._suGliScudiRemaining=Number(d._suGliScudiRemaining||0)+4;d._suGliScudiLastArmor=Number(d.armor||0);d._suGliScudiCombatKey=combatKey(c);log(s,`${d.name} ottiene +4 Armatura fino alla fine del combattimento.`);break}case'legionario_troll_attack':{const c=champ(s,p,String(t.ownChamp||''));if(c&&!c.defeated&&isStarterChamp(c)){c.tempPow=Number(c.tempPow||0)+2;if(c._legionarioProvTurn!==Number(s.turn)){c._legionarioProvPrev=!!c.provocazione;c._legionarioProvTurn=Number(s.turn)}c.provocazione=true;log(s,`${c.name} ottiene +2 POW e Provocazione fino alla fine del turno grazie a Legionario Troll.`)}break}case'falco_alba_enter':for(const z of [1,2])for(const c of player(s,z)?.champions||[])if(!c.defeated&&isStarterChamp(c))c.tempPow=Number(c.tempPow||0)+1;log(s,'Falco dell’Alba fornisce +1 POW a tutti i Campioni fino alla fine del turno.');break;case'golem_ambra_enter':{const m=monster(s,String(item.meta?.sourceUid||''));if(m){m.armor=Number(m.armor||0)+3;log(s,'Golem d’Ambra ottiene 3 Armatura.')}break}case'lascito_sciamano':summonSciamanoSupport(s,p);break}}
function updateTemporaryArmorUsage(s:any){for(const p of [1,2])for(const c of player(s,p)?.champions||[]){if(!c._suGliScudiRemaining)continue;const now=Math.max(0,Number(c.armor||0)),last=Math.max(0,Number(c._suGliScudiLastArmor??now));if(now<last)c._suGliScudiRemaining=Math.max(0,Number(c._suGliScudiRemaining)-Math.min(Number(c._suGliScudiRemaining),last-now));c._suGliScudiLastArmor=now}}
function expireCombatArmor(s:any,oldCombat:any){if(!oldCombat||s.combat)return;for(const p of [1,2])for(const c of player(s,p)?.champions||[]){if(!c._suGliScudiCombatKey)continue;const rem=Math.max(0,Number(c._suGliScudiRemaining||0));if(rem)c.armor=Math.max(0,Number(c.armor||0)-Math.min(rem,Number(c.armor||0)));delete c._suGliScudiRemaining;delete c._suGliScudiLastArmor;delete c._suGliScudiCombatKey}}
function syncDragoProvocation(s:any){const active=(s.board?.monsters||[]).some((m:any)=>m.cardId==='drago_aureo');for(const p of [1,2])for(const c of player(s,p)?.champions||[]){if(!c.supportChampion)continue;if(active&&!c._dragoAuraApplied){c._dragoAuraApplied=true;c._dragoAuraPrev=!!c.provocazione;c.provocazione=true}else if(!active&&c._dragoAuraApplied){c.provocazione=!!c._dragoAuraPrev;delete c._dragoAuraApplied;delete c._dragoAuraPrev}}}
function resetAuraMarkersOnTurn(s:any){if(Number(s._orangeAuraTurn)===Number(s.turn))return;s._orangeAuraTurn=Number(s.turn);for(const p of [1,2])for(const c of player(s,p)?.champions||[]){c._grifoneAura=0;c._soldatoAura=0}for(const m of s.board?.monsters||[]){m._grifoneAura=0;m._soldatoAura=0}}
function applyPowAura(obj:any,key:string,desired:number){let old=Number(obj[key]||0);if(Number(obj.tempPow||0)<old&&old>0)old=0;obj.tempPow=Number(obj.tempPow||0)-old+desired;obj[key]=desired}
function syncPowAuras(s:any){resetAuraMarkersOnTurn(s);const griffins=(s.board?.monsters||[]).filter((m:any)=>m.cardId==='grifone_imperiale').length;for(const p of [1,2]){const soldati=(player(s,p)?.champions||[]).filter((c:any)=>c.supportChampion&&!c.defeated&&c.id==='soldato_corrotto').length;for(const c of player(s,p)?.champions||[]){if(c.supportChampion){applyPowAura(c,'_grifoneAura',0);applyPowAura(c,'_soldatoAura',0);continue}applyPowAura(c,'_grifoneAura',c.provocazione?griffins:0);applyPowAura(c,'_soldatoAura',c.provocazione?2*soldati:0)}for(const m of s.board?.monsters||[]){applyPowAura(m,'_grifoneAura',(m.provocazione||MONSTER_DEFS[m.cardId]?.provocazione)?griffins:0);if(Number(m.owner)===p)applyPowAura(m,'_soldatoAura',(m.provocazione||MONSTER_DEFS[m.cardId]?.provocazione)?2*soldati:0)}}}
function cleanupExpiredStatus(s:any){for(const p of [1,2])for(const c of player(s,p)?.champions||[]){if(c._legionarioProvTurn!=null&&Number(c._legionarioProvTurn)!==Number(s.turn)){c.provocazione=!!c._legionarioProvPrev;delete c._legionarioProvTurn;delete c._legionarioProvPrev}}}
function killLodaAtTurnEnd(s:any,oldTurn:number){if(Number(s.turn)===oldTurn)return;for(const p of [1,2])for(const c of player(s,p)?.champions||[])if(c.supportChampion&&c.id==='loda_il_sole'&&!c.defeated){c.defeated=true;log(s,'Loda il Sole muore alla fine del turno.')}cleanupSupportDeaths(s)}
function detectNewMonsters(s:any,before:Set<string>){for(const m of s.board?.monsters||[]){if(before.has(String(m.uid)))continue;if(m.cardId==='falco_dell_alba')queueOrangeTrigger(s,{actor:Number(m.owner),sourceCardId:m.cardId,effectId:'falco_alba_enter',effectName:'Effetto — Falco dell’Alba'});if(m.cardId==='golem_d_ambra')queueOrangeTrigger(s,{actor:Number(m.owner),sourceCardId:m.cardId,effectId:'golem_ambra_enter',effectName:'Effetto — Golem d’Ambra',meta:{sourceUid:m.uid}})}}
function compensateOrangeSoulAndSciamano(s:any,before:any[],killer:number|null,excluded=false){if(excluded||!killer)return;const after=new Set((s.board?.monsters||[]).map((m:any)=>String(m.uid)));const kings=before.filter(m=>m.cardId==='re_dei_non_morti').length;for(const m of before){if(after.has(String(m.uid)))continue;if(MONSTER_DEFS[m.cardId]?.color===ORANGE)gainSoul(s,killer,ORANGE,1);if(m.cardId==='sciamano_del_sole')enqueueLascito(s,m,killer,kings)}}
function inferredKiller(s:any,move:any,top:any,oldCombat:any){if(move?.type==='pass_priority'&&top){if(top.kind==='effect'&&['enter_segugio_infernale','enter_drago_ceneri','enter_divoratore_anime'].includes(top.effectId))return null;return Number(top.actor)||null}if(move?.type==='pass_priority'&&!top&&oldCombat&&Number(s?.combatPasses||0)>=1)return Number(oldCombat.attacker?.player)||null;if(move?.type==='pass'&&Array.isArray(s?.delayedKills)&&s.delayedKills.length)return Number(s.delayedKills[0]?.killer)||null;return null}
function handleOrangeRecycle(s:any,p:number,a:any){if(s.status!=='main'||s.priority||s.stack?.length||s.combat||s.focus!==p)throw new Error('Puoi Riciclare solo con il Focus e senza Catene.');const q=player(s,p),cost=Number(q.recycleCount||0)+1,pays:any={};for(const c of ALL_COLORS)pays[c]=Number(a?.[c]||0);if(ALL_COLORS.reduce((n,c)=>n+pays[c],0)!==cost||ALL_COLORS.some(c=>pays[c]<0||pays[c]>Number(q.souls?.[c]||0)))throw new Error('Pagamento del Riciclo non valido.');if(!q.grave?.length)throw new Error('Il Cimitero è vuoto.');for(const c of ALL_COLORS)q.souls[c]=Number(q.souls?.[c]||0)-pays[c];const arr=[...(q.deck||[]),...(q.grave||[])];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}q.deck=arr;q.grave=[];q.recycleCount=cost;log(s,`${q.name} Ricicla il Cimitero pagando ${cost} Anime.`);s.focus=other(p);s.mainPasses=0;return s}
function validateOrangeCast(s:any,p:number,a:any){const c=CARD_DEFS[a.cardId],t=a.targets||{};if(!c)return;if(c.id==='sciamano_del_sole_support'&&c.tokenSupport)throw new Error('La forma Supporto di Sciamano del Sole non può essere giocata dalla mano.');if(c.id==='spacca_teste'){const x=champ(s,p,String(t.ownChamp||''));if(!x||x.defeated||x.supportChampion)throw new Error('Spacca Teste richiede un tuo Campione.')}if(c.effect==='frecce_divine'&&!monster(s,String(t.monsterUid||'')))throw new Error('Frecce Divine richiede un Mostro.');if(c.effect==='parry'||c.effect==='su_gli_scudi'){const id=String(t.ownChamp||''),x=champ(s,p,id),cb=s.combat;if(!cb||!x||x.defeated||x.supportChampion||cb.target?.type!=='champion'||Number(cb.target.player)!==p||String(cb.target.champId)!==id)throw new Error(`${c.name} richiede un tuo Campione in difesa.`)}if(c.effect==='pugno_in_faccia'){const x=support(s,p,String(t.supportId||''));if(!x||x.defeated||x.tapped)throw new Error('Pugno in Faccia richiede un tuo Supporto disponibile.');if(!legalAttackTarget(s,p,t.target))throw new Error('Bersaglio di attacco non valido.')}}

export function act(state:any,p0:any,move:any){const p=Number(p0);if(state?.pendingChoice?.type==='trigger_target'&&state.pendingChoice?.trigger?.effectId==='legionario_troll_attack'){if(move?.type!=='resolve_choice')throw new Error('C’è una scelta in attesa.');resolveOrangeChoice(state,p,move);syncDragoProvocation(state);syncPowAuras(state);return state}if(move?.type==='recycle'&&(Number(move.orange||0)>0||Number(player(state,p)?.souls?.orange||0)>0))return handleOrangeRecycle(state,p,move);if(move?.type==='cast')validateOrangeCast(state,p,move);
 cleanupExpiredStatus(state);syncDragoProvocation(state);syncPowAuras(state);updateTemporaryArmorUsage(state);const oldTurn=Number(state.turn||0),oldCombat=state.combat?clone(state.combat):null;const beforeMonsters=(state.board?.monsters||[]).map((m:any)=>clone(m)),beforeUids=new Set<string>(beforeMonsters.map((m:any)=>String(m.uid)));const top=(move?.type==='pass_priority'&&state.stack?.length)?clone(state.stack[state.stack.length-1]):null;const resolvingCustom=top?.kind==='card'&&CUSTOM_CARD_IDS.has(String(top.cardId))?{...top,effectId:CARD_DEFS[top.cardId]?.effect}:null;const resolvingOrangeEffect=top?.kind==='effect'&&['legionario_troll_attack','falco_alba_enter','golem_ambra_enter','lascito_sciamano'].includes(String(top.effectId))?top:null;const killer=inferredKiller(state,move,top,oldCombat);const excluded=!!(top?.kind==='effect'&&['enter_segugio_infernale','enter_drago_ceneri','enter_divoratore_anime'].includes(String(top.effectId)));const out=base.act(state,p,move);
 if(move?.type==='cast'&&CARD_DEFS[move.cardId]?.color===ORANGE)for(let i=Math.max(0,state.log.length-4);i<state.log.length;i++)state.log[i]=String(state.log[i]).replace('Anima Blu','Anima Arancione').replace('Anime Blu','Anime Arancioni');if(state.pendingChoice?.trigger?.effectId==='lascito_serpente'&&Number(player(state,other(Number(state.pendingChoice.player)))?.souls?.orange||0)>0&&!state.pendingChoice.options?.some((x:any)=>x.id==='orange'))state.pendingChoice.options.push({id:'orange',label:'Anima Arancione'});if(state.pendingChoice?.trigger?.effectId==='alabardo_provocazione')state.pendingChoice.options=(state.pendingChoice.options||[]).filter((o:any)=>{const c=champ(state,Number(state.pendingChoice.player),String(o.id));return c&&!c.supportChampion});compensateOrangeSoulAndSciamano(state,beforeMonsters,killer,excluded);detectNewMonsters(state,beforeUids);if(resolvingCustom&&!state.stack?.some((x:any)=>String(x.uid)===String(resolvingCustom.uid)))applyEffectResolution(state,{...resolvingCustom,effectId:resolvingCustom.effectId});if(resolvingOrangeEffect&&!state.stack?.some((x:any)=>String(x.uid)===String(resolvingOrangeEffect.uid)))applyEffectResolution(state,resolvingOrangeEffect);if(move?.type==='attack'&&state.combat){const a=champ(state,p,String(state.combat.attacker?.champId||''));if(a)onCombatDeclared(state,p,a,state.combat.target)}if(oldCombat&&move?.type==='pass_priority'&&!top&&!state.combat&&oldCombat.target?.type==='monster'){const def=beforeMonsters.find((m:any)=>String(m.uid)===String(oldCombat.target.uid));if(def?.cardId==='leone_solare'&&!oldCombat.cancelled){const n=Math.max(0,monsterPow({...(state||{}),board:{monsters:beforeMonsters}},def));const atk=champ(state,Number(oldCombat.attacker.player),String(oldCombat.attacker.champId));if(atk&&!atk.defeated&&n>0){log(state,`Leone Solare contrattacca con ${n} POW.`);damageChampionLocal(state,Number(oldCombat.attacker.player),String(oldCombat.attacker.champId),n,'Leone Solare')}}}updateTemporaryArmorUsage(state);expireCombatArmor(state,oldCombat);killLodaAtTurnEnd(state,oldTurn);cleanupExpiredStatus(state);cleanupSupportDeaths(state);syncDragoProvocation(state);syncPowAuras(state);processOrangeTriggers(state);checkWinner(state);return out}
