import * as base from './game-v51-loader.ts?rev=d33838ee';

export const CARD_DEFS:any=base.CARD_DEFS;
export const MONSTER_DEFS:any=base.MONSTER_DEFS;
export const CHAMPION_DEFS:any=base.CHAMPION_DEFS;
export const DECK_RULES=base.DECK_RULES;

Object.assign(MONSTER_DEFS,{
  minotauro_infernale:{id:'minotauro_infernale',name:'Minotauro Infernale',color:'red',pow:4,text:'Quando questo Mostro entra in gioco, tutti i giocatori scartano 1 carta dalla loro mano.'},
  treant_millenario:{id:'treant_millenario',name:'Treant Millenario',color:'green',pow:3,text:'Quando subisce danni ottiene 2 Armatura.'},
  ghoul_affamato:{id:'ghoul_affamato',name:'Ghoul Affamato',color:'black',pow:1,text:'Quando muore un altro Mostro, le Magie di costo 3 o superiore costano 1 Anima in meno per questo turno.'},
  balena_della_tempesta:{id:'balena_della_tempesta',name:'Balena della Tempesta',color:'blue',pow:4,text:'Quando entra in gioco riduce di 1 il POW a tutti i Campioni.'},
  scarabeo_dorato:{id:'scarabeo_dorato',name:'Scarabeo Dorato',color:'orange',pow:2,text:'Lascito — Pesca 1 carta.',lascito:'scarabeo_dorato'}
});

const NEW_MONSTERS=['minotauro_infernale','treant_millenario','ghoul_affamato','balena_della_tempesta','scarabeo_dorato'];
export const STARTER_DECK=base.STARTER_DECK;
export const STARTER_MONSTERS=[...new Set([...(base.STARTER_MONSTERS||[]),...NEW_MONSTERS])];
export const newPlayer=base.newPlayer;
export const newState=base.newState;

const other=(p:number)=>p===1?2:1;
const player=(s:any,p:number)=>s?.players?.[String(p)]||null;
const champ=(s:any,p:number,id:any)=>(player(s,p)?.champions||[]).find((c:any)=>String(c?.id)===String(id));
const log=(s:any,msg:string)=>{s.log ||= [];s.log.push(msg);if(s.log.length>180)s.log=s.log.slice(-180)};

function championPow(s:any,p:number,c:any){if(!c)return 1;let v=Number(c.basePow??CHAMPION_DEFS?.[c.id]?.basePow??0)+Number(c.tempPow||0);if(String(c.id)==='kael'&&(player(s,p)?.hand?.length||0)===0&&s?.status==='main')v+=3;return Math.max(1,v)}
function terminalGameover(s:any){if(!s?.players)return;for(const p of [1,2]){const starters=(player(s,p)?.champions||[]).filter((c:any)=>!c.supportChampion);if(starters.length&&starters.every((c:any)=>!!c.defeated)){const win=other(p);if(s.status!=='gameover'||Number(s.winner)!==win){s.status='gameover';s.winner=win;const last=String((s.log||[])[(s.log||[]).length-1]||'');if(!last.includes('vince la partita'))log(s,`${player(s,win)?.name||`Giocatore ${win}`} vince la partita!`)}s.priority=null;s.priorityPasses=0;s.mainPasses=0;s.stack=[];s.stackInitiator=null;s.combat=null;s.pendingChoice=null;s.triggerQueue=[];s.enterQueue=[];s.delayedKills=[];s.endTurnPending=false;return}}}
function woundChampion(s:any,p:number,c:any,source:string){if(!c||c.defeated)return;c.wounds=Number(c.wounds||0)+1;c.damage=0;log(s,`${c.name} subisce una Ferita (${c.wounds}/${c.hp})${source?` da ${source}`:''}.`);if(c.wounds>=Number(c.hp||1)){c.defeated=true;c.tapped=true;log(s,`${c.name} è sconfitto.`)}}
function damageChampion(s:any,p:number,id:string,n:number,source:string){const c=champ(s,p,id);if(!c||c.defeated||n<=0)return;let left=n;const armor=Math.max(0,Number(c.armor||0)),blocked=Math.min(armor,left);if(blocked){c.armor=armor-blocked;left-=blocked;log(s,`${c.name} usa ${blocked} Armatura e annulla ${blocked} dann${blocked===1?'o':'i'}.`)}if(left<=0)return;c.damage=Number(c.damage||0)+left;const threshold=championPow(s,p,c);log(s,`${c.name} subisce ${left} dann${left===1?'o':'i'} (${c.damage}/${threshold}).`);if(c.damage>=threshold)woundChampion(s,p,c,source)}

function snapshot(s:any){const board=new Map<string,any>();for(const m of s?.board?.monsters||[])board.set(String(m.uid),{uid:String(m.uid),cardId:String(m.cardId),owner:Number(m.owner),damage:Number(m.damage||0),armor:Number(m.armor||0)});return{turn:Number(s?.turn||0),board}}
function resetTurnFlags(s:any,oldTurn:number){if(Number(s?.turn)===Number(oldTurn))return;for(const p of [1,2]){const q=player(s,p);if(!q)continue;delete q._ghoulDiscountTurn;delete q._ghoulDiscountAmount}}
function ghoulDiscount(s:any,p:number,c:any){const q=player(s,p);if(!q||!c||c.type!=='Magia'||Number(c.cost||0)<3)return 0;return Number(q._ghoulDiscountTurn)===Number(s.turn)?Math.max(0,Number(q._ghoulDiscountAmount||0)):0}
function withGhoulAdjustedCast(s:any,p:number,move:any,fn:()=>any){if(move?.type!=='cast')return fn();const c=CARD_DEFS?.[String(move.cardId||'')],q=player(s,p);if(!c||!q)return fn();const gh=ghoulDiscount(s,p,c);if(!gh)return fn();const original=Number(c.cost||0);const grinn=(c.type==='Magia'&&original>=3&&Number(q._grinnDiscountTurn)===Number(s.turn))?1:0;const oldGrinn=q._grinnDiscountTurn;c.cost=Math.max(0,original-gh-grinn);if(grinn)q._grinnDiscountTurn=-999999;try{return fn()}finally{c.cost=original;if(oldGrinn===undefined)delete q._grinnDiscountTurn;else q._grinnDiscountTurn=oldGrinn}}

function applyScarletDiscard(s:any,p:number){const q=player(s,p),c=champ(s,p,'scarlet');if(!q||!c||c.defeated||Number(q._scarletTriggeredTurn)===Number(s.turn))return;q._scarletTriggeredTurn=Number(s.turn);const i=(q.deck||[]).findIndex((id:string)=>CARD_DEFS[id]?.color==='red');if(i<0){log(s,'Fuoco e Fiamme non trova una carta Rossa nel Mazzo.');return}const[id]=q.deck.splice(i,1);q.hand ||= [];q.hand.push(id);log(s,`Fuoco e Fiamme: ${q.name} pesca ${CARD_DEFS[id]?.name||id}.`)}
function queueMinotauroDiscards(s:any,owner:number){s._v52MinotauroDiscards ||= [];for(const p of [owner,other(owner)])if((player(s,p)?.hand||[]).length)s._v52MinotauroDiscards.push({player:p})}
function promoteMinotauroChoice(s:any){if(s.pendingChoice||s.status==='gameover')return;const q=s._v52MinotauroDiscards;while(Array.isArray(q)&&q.length){const x=q.shift(),pl=player(s,Number(x.player));if(!pl||(pl.hand||[]).length===0)continue;s.pendingChoice={type:'v52_minotauro_discard',player:Number(x.player),sourceCardId:'minotauro_infernale',cardIds:[...pl.hand]};s.priority=null;log(s,`${pl.name} deve scartare 1 carta per Minotauro Infernale.`);return}if(Array.isArray(q)&&!q.length)delete s._v52MinotauroDiscards}
function resolveMinotauroChoice(s:any,p:number,a:any){const pc=s.pendingChoice,q=player(s,p);if(!pc||pc.type!=='v52_minotauro_discard'||Number(pc.player)!==p)throw new Error('Scelta non valida.');if(a?.type!=='resolve_choice')throw new Error('C’è una scelta in attesa.');const id=String(a.cardId||a.choice||'');const i=(q?.hand||[]).indexOf(id);if(i<0||!(pc.cardIds||[]).includes(id))throw new Error('Carta da scartare non valida.');q.hand.splice(i,1);q.grave ||= [];q.grave.push(id);s.pendingChoice=null;log(s,`${q.name} scarta ${CARD_DEFS[id]?.name||id} per Minotauro Infernale.`);applyScarletDiscard(s,p);promoteMinotauroChoice(s);return s}

function applyTreantDamageTriggers(s:any,before:any){for(const m of s?.board?.monsters||[]){if(String(m.cardId)!=='treant_millenario')continue;const b=before.board.get(String(m.uid));if(!b)continue;if(Number(m.damage||0)>Number(b.damage||0)){m.armor=Number(m.armor||0)+2;log(s,'Treant Millenario subisce danni e ottiene 2 Armatura.')}}}
function applyGhoulDeaths(s:any,before:any){const alive=new Set((s?.board?.monsters||[]).map((m:any)=>String(m.uid)));const dead=[...before.board.values()].filter((m:any)=>!alive.has(String(m.uid)));if(!dead.length)return;const ghouls=[...before.board.values()].filter((m:any)=>m.cardId==='ghoul_affamato');for(const g of ghouls){const count=dead.filter((d:any)=>String(d.uid)!==String(g.uid)).length;if(!count)continue;const q=player(s,Number(g.owner));if(!q)continue;if(Number(q._ghoulDiscountTurn)!==Number(s.turn)){q._ghoulDiscountTurn=Number(s.turn);q._ghoulDiscountAmount=0}q._ghoulDiscountAmount=Number(q._ghoulDiscountAmount||0)+count;log(s,`Ghoul Affamato: le Magie di costo 3 o superiore di ${q.name} costano ${q._ghoulDiscountAmount} Anima${q._ghoulDiscountAmount===1?'':'e'} in meno per questo turno.`)}}
function kingsBefore(before:any){return [...before.board.values()].filter((m:any)=>m.cardId==='re_dei_non_morti').length}
function applyScarabeoLascito(s:any,before:any){const alive=new Set((s?.board?.monsters||[]).map((m:any)=>String(m.uid))),kings=kingsBefore(before);for(const d of before.board.values()){if(d.cardId!=='scarabeo_dorato'||alive.has(String(d.uid)))continue;const q=player(s,Number(d.owner));if(!q)continue;const count=1+kings;for(let i=0;i<count;i++){const id=q.deck?.shift?.();if(id){q.hand ||= [];q.hand.push(id);log(s,`Lascito — Scarabeo Dorato: ${q.name} pesca ${CARD_DEFS[id]?.name||id}.`)}else log(s,'Lascito — Scarabeo Dorato non trova carte da pescare.')}}}
function applyNewEntries(s:any,before:any){const known=new Set(before.board.keys());const entered=(s?.board?.monsters||[]).filter((m:any)=>!known.has(String(m.uid)));for(const m of entered){if(m.cardId==='minotauro_infernale')queueMinotauroDiscards(s,Number(m.owner));else if(m.cardId==='balena_della_tempesta'){for(const p of [1,2])for(const c of [...(player(s,p)?.champions||[])])if(!c.defeated){c.tempPow=Number(c.tempPow||0)-1;log(s,`Balena della Tempesta riduce di 1 il POW di ${c.name}.`)}}}}

export function act(state:any,p0:any,move:any){const p=Number(p0);if(state?.pendingChoice?.type==='v52_minotauro_discard')return resolveMinotauroChoice(state,p,move);const before=snapshot(state),oldTurn=Number(state?.turn||0);const out=withGhoulAdjustedCast(state,p,move,()=>base.act(state,p,move));resetTurnFlags(state,oldTurn);applyTreantDamageTriggers(state,before);applyGhoulDeaths(state,before);applyScarabeoLascito(state,before);applyNewEntries(state,before);terminalGameover(state);promoteMinotauroChoice(state);return out||state}
export function publicView(state:any,p0:any){promoteMinotauroChoice(state);const p=Number(p0),v:any=base.publicView(state,p),q=player(state,p);const gh=Number(q?._ghoulDiscountTurn)===Number(state.turn)?Math.max(0,Number(q?._ghoulDiscountAmount||0)):0;if(gh&&v?.players?.[String(p)]?.handCards){for(const c of v.players[String(p)].handCards){const d=CARD_DEFS?.[c.id];if(d?.type==='Magia'&&Number(d.cost||0)>=3)c.effectiveCost=Math.max(0,Number(c.effectiveCost??c.cost??d.cost)-gh)}}for(const z of [1,2]){const x=v?.players?.[String(z)];if(!x)continue;delete x._ghoulDiscountTurn;delete x._ghoulDiscountAmount}delete v._v52MinotauroDiscards;return v}
