import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
globalThis.fetch=async input=>new Response(await fs.readFile(new URL('../soulforge/'+String(input).split('/').pop().split('?')[0],import.meta.url),'utf8'));
const game=await import('../soulforge/game-v62-loader.ts');
const {engine61:E}=await import('../soulforge/game-v32-loader.ts?rev=souls-uncapped-v3');
const {cards,monsters}=await import('../soulforge/new20-catalog.js');
const cp=(p,id)=>({type:'champion',player:p,champId:id});
function fresh(){
 const deck={champions:['scarlet','torvald'],cards:Object.values(game.CARD_DEFS).filter(x=>['red','green'].includes(x.color)&&!x.tokenSupport).slice(0,18).map(x=>x.id),monsters:Object.values(game.MONSTER_DEFS).filter(x=>['red','green'].includes(x.color)).slice(0,12).map(x=>x.id)};
 const s=game.newState('A',deck);s.players[2]=game.newPlayer('B',deck);
 Object.assign(s,{status:'main',turn:3,focus:1,priority:null,stack:[],stackInitiator:null,combat:null,pendingChoice:null,triggerQueue:[],enterQueue:[],log:[],board:{monsters:[]}});
 for(const p of [1,2]){Object.assign(s.players[p],{hand:[],grave:[],monsterGrave:[],selected:true,deckColors:['red','green','black','blue','orange'],souls:{red:100,green:100,black:100,blue:100,orange:100}});for(const c of s.players[p].champions)Object.assign(c,{basePow:5,hp:10,damage:0,wounds:0,armor:0,tempPow:0,tapped:false})}return s;
}
const champ=(s,p=1)=>s.players[p].champions[0];
function mon(s,id,owner=1){const m={uid:crypto.randomUUID(),cardId:id,owner,damage:0,tempPow:0,powMod:0,armor:0};s.board.monsters.push(m);return m}
const pass=s=>game.act(s,Number(s.priority),{type:'pass_priority'});
function drain(s){let n=0;while((s.stack.length||s.combat)&&!s.pendingChoice){assert.ok(n++<50,'trigger loop');pass(s)}}
function cast(s,id,targets={}){s.focus=1;s.players[1].hand.push(id);game.act(s,1,{type:'cast',cardId:id,targets})}
function spell(s,id,targets={}){cast(s,id,targets);drain(s)}
function enter(s,id,owner=1){const m=E.addMonster(s,id,owner);E.prepare(s);return m}
const tests=[];const test=(n,f)=>tests.push([n,f]);
test('7 carte e 13 Mostri: tutte le 20 definizioni',()=>{assert.equal(cards.length+monsters.length,20);for(const x of cards)assert.equal(game.CARD_DEFS[x.id].cost,x.cost);for(const x of monsters)assert.equal(game.MONSTER_DEFS[x.id].pow,x.pow)});
test('Tesoro pesca 3 carte',()=>{const s=fresh();s.players[1].deck=['linfa_vitale','stupido','riflesso'];spell(s,'tesoro_del_sovrano');assert.equal(s.players[1].hand.length,3)});
test('Araldo guadagna POW una volta per ciascuna carta pescata',()=>{const s=fresh();spell(s,'araldo_dell_opulenza');s.players[1].deck=['linfa_vitale','stupido','riflesso'];spell(s,'tesoro_del_sovrano');assert.equal(s.players[1].champions.find(x=>x.sourceCardId==='araldo_dell_opulenza').tempPow,3)});
test('Viaggiatore usa la differenza di carte, costo minimo zero',()=>{const s=fresh();s.players[1].hand=['a','b','c','d','e'];cast(s,'viaggiatore_smarrito');assert.equal(s.stack[0].paidCost,0);drain(s);assert.ok(s.players[1].champions.some(x=>x.sourceCardId==='viaggiatore_smarrito'))});
test('Furia supporto reagisce solo a danni effettivi sopravvissuti',()=>{const s=fresh();spell(s,'furia_del_ferito_supporto');const x=s.players[1].champions.find(x=>x.sourceCardId==='furia_del_ferito_supporto');x.hp=5;E.damageChampion(s,1,x.id,1,'test');E.prepare(s);drain(s);assert.equal(x.tempPow,2);x.armor=3;E.damageChampion(s,1,x.id,1,'test');E.prepare(s);drain(s);assert.equal(x.tempPow,2)});
test('Munizioni scarta subito come costo e colpisce in risoluzione',()=>{const s=fresh(),m=mon(s,'lucertola_fuoco');s.players[1].hand=['linfa_vitale'];cast(s,'munizioni_d_emergenza',{discardId:'linfa_vitale',target:{type:'monster',uid:m.uid}});assert.deepEqual(s.players[1].grave,['linfa_vitale']);assert.equal(m.damage,0);drain(s);assert.equal(s.board.monsters.length,0)});
test('Munizioni non può scartare se stessa',()=>{const s=fresh(),m=mon(s,'lucertola_fuoco');s.players[1].hand=['munizioni_d_emergenza'];assert.throws(()=>game.act(s,1,{type:'cast',cardId:'munizioni_d_emergenza',targets:{discardId:'munizioni_d_emergenza',target:{type:'monster',uid:m.uid}}}));assert.deepEqual(s.players[1].hand,['munizioni_d_emergenza'])});
test('Pappagallo mette in pila il danno e non dà anime',()=>{const s=fresh();const m=enter(s,'pappagallo_pirata');assert.equal(m.damage,0);assert.ok(s.stack.some(x=>x.effectId==='new20_pappagallo'));drain(s);assert.equal(m.damage,1)});
test('Tartaruga potenzia solo i Mostri con POW attuale massimo 2',()=>{const s=fresh(),low=mon(s,'mantide_della_giungla'),high=mon(s,'lucertola_fuoco');enter(s,'tartaruga_delle_radici');drain(s);assert.equal(low.tempPow,2);assert.equal(high.tempPow,0)});
test('Serpente riduce solo i vicini',()=>{const s=fresh(),a=mon(s,'lucertola_fuoco'),b=mon(s,'lucertola_fuoco');enter(s,'serpente_glaciale');drain(s);assert.equal(a.tempPow,0);assert.equal(b.tempPow,-1)});
test('Serafino concede Provocazione al vicino sinistro',()=>{const s=fresh(),a=mon(s,'lucertola_fuoco');enter(s,'serafino_guardiano');drain(s);assert.equal(a.provocazione,true)});
test('Sfinge pesca per entrambi',()=>{const s=fresh();s.players[1].deck=['linfa_vitale'];s.players[2].deck=['stupido'];enter(s,'sfinge_dell_alba');drain(s);assert.deepEqual(s.players[1].hand,['linfa_vitale']);assert.deepEqual(s.players[2].hand,['stupido'])});
test('Mantide rifiuta Magie nuove e vecchie, non i danni globali',()=>{const s=fresh(),m=mon(s,'mantide_della_giungla');s.players[1].hand=['munizioni_d_emergenza','linfa_vitale'];assert.throws(()=>game.act(s,1,{type:'cast',cardId:'munizioni_d_emergenza',targets:{discardId:'linfa_vitale',target:{type:'monster',uid:m.uid}}}));s.players[1].hand.push('colpo_di_cannone');assert.throws(()=>game.act(s,1,{type:'cast',cardId:'colpo_di_cannone',targets:{enemy:{type:'monster',uid:m.uid}}}));E.damageMonster(s,1,m.uid,1,'globale');assert.equal(m.damage,1)});
test('Cobra protegge solo il giocatore con più carte, parità nessuno',()=>{const s=fresh();mon(s,'cobra_reale');s.players[1].hand=['linfa_vitale'];E.damageChampion(s,1,champ(s).id,1,'test');assert.equal(champ(s).damage,0);E.damageChampion(s,2,champ(s,2).id,1,'test');assert.equal(champ(s,2).damage,1);s.players[2].hand=['stupido'];E.damageChampion(s,1,champ(s).id,1,'test');assert.equal(champ(s).damage,1)});
test('Demone concede Carica solo all’attaccante',()=>{const s=fresh();mon(s,'demone_della_fornace');assert.equal(E.pow(s,1,champ(s)),5);game.act(s,1,{type:'attack',champId:champ(s).id,target:cp(2,champ(s,2).id)});assert.equal(E.pow(s,1,champ(s)),6);assert.equal(E.pow(s,2,champ(s,2)),5);drain(s);assert.equal(E.pow(s,1,champ(s)),5)});
test('Viverna apre un trigger rispondibile prima del combattimento',()=>{const s=fresh();mon(s,'viverna');game.act(s,1,{type:'attack',champId:champ(s).id,target:cp(2,champ(s,2).id)});assert.equal(champ(s).damage,0);assert.ok(s.stack.some(x=>x.effectId==='new20_viverna'));assert.equal(s.priority,2);pass(s);assert.equal(champ(s).damage,1);assert.equal(champ(s,2).damage,1);assert.ok(s.combat)});
test('Tritone aggiunge armatura una volta e Idra genera un trigger',()=>{const s=fresh();mon(s,'tritone_del_gelo');mon(s,'idra_della_palude');cast(s,'egida_d_acciaio',{target:cp(1,champ(s).id)});pass(s);assert.equal(champ(s).armor,3);assert.ok(s.stack.some(x=>x.effectId==='new20_idra'));drain(s);assert.equal(champ(s).armor,2)});
test('Granchio applica e rimuove Provocazione con l’armatura',()=>{const s=fresh();mon(s,'granchio_degli_abissi');const m=mon(s,'lucertola_fuoco',2);m.armor=2;game.publicView(s,1);assert.equal(m.provocazione,true);m.armor=0;game.publicView(s,1);assert.equal(m.provocazione,false)});
test('Ragno permette scelte illustrate separate per entrambi',()=>{const s=fresh();s.players[1].grave=['linfa_vitale'];s.players[2].grave=['stupido'];enter(s,'ragno_dei_cadaveri');drain(s);assert.equal(s.pendingChoice.player,1);game.act(s,1,{type:'resolve_choice',cardId:'linfa_vitale'});assert.equal(s.pendingChoice.player,2);game.act(s,2,{type:'resolve_choice',cardId:'stupido'});assert.equal(s.pendingChoice,null);assert.deepEqual(s.players[1].hand,['linfa_vitale']);assert.deepEqual(s.players[2].hand,['stupido'])});
test('Angelo sceglie dal mazzo e mette la carta bersagliata in pila',()=>{const s=fresh();s.players[1].deck=['linfa_vitale','stupido'];spell(s,'angelo');assert.equal(s.pendingChoice.type,'new20_angelo');game.act(s,1,{type:'resolve_choice',cardId:'linfa_vitale',targets:{target:cp(1,champ(s).id)}});assert.ok(s.stack.some(x=>x.cardId==='linfa_vitale'));assert.deepEqual(s.players[1].deck,['stupido']);assert.deepEqual(game.publicView(s,1).stack.at(-1).targetRefs,game.publicView(s,2).stack.at(-1).targetRefs);drain(s)});
test('Bronzo evoca dalla mano costi differenti e attiva Angelo',()=>{const s=fresh();s.players[1].hand=['angelo','araldo_dell_opulenza'];s.players[1].deck=['linfa_vitale'];spell(s,'guerriero_di_bronzo');assert.equal(s.pendingChoice.type,'new20_bronzo');game.act(s,1,{type:'resolve_choice',cardIds:['angelo','araldo_dell_opulenza']});drain(s);assert.ok(s.players[1].champions.some(x=>x.sourceCardId==='angelo'));assert.equal(s.pendingChoice.type,'new20_angelo')});
test('Bonus Tartaruga e Serafino scadono a fine turno',()=>{const s=fresh(),low=mon(s,'mantide_della_giungla');enter(s,'tartaruga_delle_radici');drain(s);enter(s,'serafino_guardiano');drain(s);game.act(s,s.focus,{type:'pass'});game.act(s,s.focus,{type:'pass'});assert.equal(low.tempPow,0);assert.ok(s.board.monsters.every(x=>!x.provocazione62Turn))});
test('Araldo e Guardiano aggiungono una sola carta bonus per pescata multipla',()=>{const s=fresh();spell(s,'araldo_dell_opulenza');mon(s,'guardiano_del_tesoro');s.players[1].deck=['linfa_vitale','stupido','riflesso','taglio_ninjitsu','sfera_incandescente'];spell(s,'tesoro_del_sovrano');assert.equal(s.players[1].hand.length,4);assert.equal(s.players[1].champions.find(x=>x.sourceCardId==='araldo_dell_opulenza').tempPow,4)});
test('Angelo paga le tasse di Ragno dei Germogli e permette bersagli della carta scelta',()=>{const s=fresh();mon(s,'ragno_dei_germogli');s.players[1].deck=['linfa_vitale'];spell(s,'angelo');const before=s.players[1].souls.green;game.act(s,1,{type:'resolve_choice',cardId:'linfa_vitale',targets:{target:cp(1,champ(s).id)}});assert.equal(s.players[1].souls.green,before-1);assert.equal(s.stack.at(-1).paidCost,1)});
test('Bronzo rifiuta due Supporti dello stesso costo senza consumarli',()=>{const s=fresh();s.players[1].hand=['angelo','furia_del_ferito_supporto'];spell(s,'guerriero_di_bronzo');assert.throws(()=>game.act(s,1,{type:'resolve_choice',cardIds:['angelo','furia_del_ferito_supporto']}));assert.ok(s.players[1].hand.includes('angelo'));assert.ok(s.players[1].hand.includes('furia_del_ferito_supporto'))});
test('Viverna mostra entrambi i partecipanti a entrambi i giocatori',()=>{const s=fresh();mon(s,'viverna');game.act(s,1,{type:'attack',champId:champ(s).id,target:cp(2,champ(s,2).id)});const a=game.publicView(s,1).stack.at(-1),b=game.publicView(s,2).stack.at(-1);assert.equal(a.targetRefs.length,2);assert.deepEqual(a.targetRefs,b.targetRefs)});
test('Monocolore: entrambi i giocatori partono con 2 anime, non 4',()=>{
 const d={champions:['scarlet','kael'],cards:Object.values(game.CARD_DEFS).filter(x=>x.color==='red'&&!x.tokenSupport).slice(0,18).map(x=>x.id),monsters:Object.values(game.MONSTER_DEFS).filter(x=>x.color==='red').slice(0,12).map(x=>x.id)};
 const s=game.newState('A',d);s.players[2]=game.newPlayer('B',d);s.status='select';
 for(const p of [1,2])assert.deepEqual(s.players[p].souls,{red:2,green:0,black:0,blue:0,orange:0});
 game.act(s,1,{type:'select_cards',cardIds:s.players[1].deck.slice(0,6)});game.act(s,2,{type:'select_cards',cardIds:s.players[2].deck.slice(0,6)});
 for(const p of [1,2])assert.equal(s.players[p].souls.red,2);
});
test('Corregge vecchie stanze iniziali senza azzerare anime in partita',()=>{
 const s=fresh();s.turn=1;s.status='select';for(const p of [1,2])s.players[p].souls.red=4;
 game.publicView(s,1);for(const p of [1,2])assert.deepEqual(s.players[p].souls,{red:2,green:2,black:0,blue:0,orange:0});
 s.status='main';s.players[1].souls.red=7;game.publicView(s,1);assert.equal(s.players[1].souls.red,7);
});
let failed=0;for(const [name,fn] of tests){try{fn();console.log('✓ '+name)}catch(e){failed++;console.error('✗ '+name+'\n'+e.stack)}}console.log(`${tests.length-failed}/${tests.length} passed`);process.exitCode=failed?1:0;
