import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
globalThis.fetch=async input=>new Response(await fs.readFile(new URL('../soulforge/'+String(input).split('/').pop().split('?')[0],import.meta.url),'utf8'));
const game=await import('../soulforge/game-v63-loader.ts');
const {engine61:E}=await import('../soulforge/game-v32-loader.ts?rev=souls-uncapped-v3');
const {cards}=await import('../soulforge/batch3-catalog.js');
const cp=(p,id)=>({type:'champion',player:p,champId:id}),mr=m=>({type:'monster',uid:m.uid});
function fresh(){
 const deck={champions:['scarlet','torvald'],cards:Object.values(game.CARD_DEFS).filter(x=>['red','green'].includes(x.color)&&!x.tokenSupport).slice(0,18).map(x=>x.id),monsters:Object.values(game.MONSTER_DEFS).filter(x=>['red','green'].includes(x.color)).slice(0,12).map(x=>x.id)};
 const s=game.newState('A',deck);s.players[2]=game.newPlayer('B',deck);
 Object.assign(s,{status:'main',turn:3,focus:1,priority:null,stack:[],stackInitiator:null,combat:null,pendingChoice:null,triggerQueue:[],enterQueue:[],log:[],board:{monsters:[]}});
 for(const p of [1,2]){Object.assign(s.players[p],{hand:[],grave:[],monsterGrave:[],selected:true,deckColors:['red','green','black','blue','orange'],souls:{red:100,green:100,black:100,blue:100,orange:100}});for(const c of s.players[p].champions)Object.assign(c,{basePow:8,hp:10,damage:0,wounds:0,armor:0,tempPow:0,tapped:false})}return s;
}
const champ=(s,p=1)=>s.players[p].champions[0];
function mon(s,id='lucertola_fuoco',owner=1){const m={uid:crypto.randomUUID(),cardId:id,owner,damage:0,tempPow:0,powMod:0,armor:0};s.board.monsters.push(m);return m}
const pass=s=>game.act(s,Number(s.priority),{type:'pass_priority'});
function drain(s){let n=0;while((s.stack.length||s.combat)&&!s.pendingChoice){assert.ok(n++<100,'trigger loop');pass(s)}}
function cast(s,id,targets={}){s.focus=1;s.players[1].hand.push(id);game.act(s,1,{type:'cast',cardId:id,targets})}
function spell(s,id,targets={}){cast(s,id,targets);drain(s)}
function end(s){game.act(s,s.focus,{type:'pass'});game.act(s,s.focus,{type:'pass'})}
const tests=[];const test=(n,f)=>tests.push([n,f]);
test('Tutte e 20 definite; Richiamo verde distinto dalla carta nera',()=>{assert.equal(cards.length,20);for(const x of cards)assert.equal(game.CARD_DEFS[x.id].cost,x.cost);assert.equal(game.CARD_DEFS.richiamo_del_branco.color,'black');assert.equal(game.CARD_DEFS.richiamo_del_branco_verde.color,'green')});
test('Vincolo: costo di tap immediato, riduzione solo in risoluzione',()=>{const s=fresh(),m=mon(s);cast(s,'vincolo_di_brina',{champion:cp(1,champ(s).id),enemy:mr(m)});assert.equal(champ(s).tapped,true);assert.equal(m.tempPow,0);drain(s);assert.equal(m.tempPow,-2)});
test('Vincolo: costo non pagabile non consuma carta o anime',()=>{const s=fresh(),m=mon(s);champ(s).tapped=true;s.players[1].hand=['vincolo_di_brina'];assert.throws(()=>game.act(s,1,{type:'cast',cardId:'vincolo_di_brina',targets:{champion:cp(1,champ(s).id),enemy:mr(m)}}));assert.deepEqual(s.players[1].hand,['vincolo_di_brina'])});
test('Vincolo riduce anche il Campione avversario',()=>{const s=fresh();spell(s,'vincolo_di_brina',{champion:cp(1,champ(s).id),enemy:cp(2,champ(s,2).id)});assert.equal(champ(s,2).tempPow,-2)});
test('Esazione riduce di uno solo il colore scelto',()=>{const s=fresh();spell(s,'esazione_delle_anime',{color:'blue'});assert.equal(s.players[2].souls.blue,99);assert.equal(s.players[2].souls.red,100)});
test('Richiamo Sepolcrale evoca dal proprio Cimitero e attiva entrata',()=>{const s=fresh();s.players[1].monsterGrave=['pappagallo_pirata'];spell(s,'richiamo_sepolcrale',{graveMonsterId:'pappagallo_pirata'});assert.equal(s.players[1].monsterGrave.length,0);assert.equal(s.board.monsters[0].damage,1)});
test('Rinascita: ritorna senza danni, bonus o effetti di entrata',()=>{const s=fresh(),m=mon(s,'pappagallo_pirata');m.tempPow=4;m.damage=1;spell(s,'rinascita',{target:mr(m)});spell(s,'mandato_di_morte',{target:mr(m)});const revived=s.board.monsters.find(x=>x.cardId==='pappagallo_pirata');assert.ok(revived);assert.notEqual(revived.uid,m.uid);assert.equal(revived.damage,0);assert.equal(revived.tempPow,0);assert.equal(revived.rinascita63,undefined);assert.ok(!s.stack.length);spell(s,'mandato_di_morte',{target:mr(revived)});assert.equal(s.board.monsters.length,0)});
test('Rinascita conserva e attiva il Lascito originale',()=>{const s=fresh(),m=mon(s,'custode_sepolcrale');assert.ok(game.MONSTER_DEFS[m.cardId]?.lascito);spell(s,'rinascita',{target:mr(m)});spell(s,'mandato_di_morte',{target:mr(m)});assert.ok(s.board.monsters.some(x=>x.cardId===m.cardId));assert.equal(champ(s).tempPow,1)});
test('Marea colpisce tutti i Mostri e cura solo i tuoi Campioni',()=>{const s=fresh(),a=mon(s),b=mon(s,'lucertola_fuoco',2);champ(s).damage=3;champ(s,2).damage=3;spell(s,'marea_necrotica');assert.equal(a.damage,1);assert.equal(b.damage,1);assert.equal(champ(s).damage,2);assert.equal(champ(s,2).damage,3)});
test('Corazza accumula 2 armatura per ogni morte e scade al turno',()=>{const s=fresh(),a=mon(s),b=mon(s);spell(s,'corazza_dei_caduti',{target:cp(1,champ(s).id)});spell(s,'mandato_di_morte',{target:mr(a)});spell(s,'mandato_di_morte',{target:mr(b)});assert.equal(champ(s).armor,4);end(s);assert.equal(champ(s).armor,0)});
test('Sifone: due bersagli, danno e cura indipendenti',()=>{const s=fresh(),m=mon(s);champ(s).damage=4;spell(s,'sifone_d_anime',{enemy:mr(m),champion:cp(1,champ(s).id)});assert.equal(m.damage,1);assert.equal(champ(s).damage,2)});
test('Lascito Profanato attiva senza uccidere o dare anime',()=>{const s=fresh(),m=mon(s,'custode_sepolcrale');const souls=s.players[1].souls.black;spell(s,'lascito_profanato',{target:mr(m)});assert.ok(s.board.monsters.includes(m));assert.equal(s.players[1].monsterGrave.length,0);assert.equal(s.players[1].souls.black,souls);assert.equal(champ(s).tempPow,1)});
test('Lascito Profanato rifiuta POW elevato e bersagli nel cimitero',()=>{const s=fresh(),m=mon(s);m.tempPow=10;s.players[1].hand=['lascito_profanato'];assert.throws(()=>game.act(s,1,{type:'cast',cardId:'lascito_profanato',targets:{target:mr(m)}}));assert.throws(()=>game.act(s,1,{type:'cast',cardId:'lascito_profanato',targets:{target:{type:'monster',uid:'grave'}}}))});
test('Risveglio attiva tutti e solo i tuoi Campioni',()=>{const s=fresh();for(const p of [1,2])for(const c of s.players[p].champions)c.tapped=true;spell(s,'risveglio_selvaggio');assert.ok(s.players[1].champions.every(c=>!c.tapped));assert.ok(s.players[2].champions.every(c=>c.tapped))});
test('Guardiano delle Radici concede bonus e Provocazione temporanei',()=>{const s=fresh(),m=mon(s);spell(s,'guardiano_delle_radici',{target:mr(m)});assert.equal(m.tempPow,4);assert.equal(m.provocazione,true);end(s);assert.equal(m.tempPow,0);assert.equal(m.provocazione,false)});
test('Richiamo verde impedisce nuove Provocazioni nel turno',()=>{const s=fresh(),m=mon(s);spell(s,'richiamo_del_branco_verde',{target:mr(m)});spell(s,'guardiano_delle_radici',{target:mr(m)});assert.equal(game.publicView(s,1).board.monsters[0].provocazione,false)});
test('Spaccacorazze: 1 senza armatura, 3 prima dell’assorbimento',()=>{const s=fresh(),m=mon(s);m.tempPow=10;m.armor=1;spell(s,'spaccacorazze_della_giungla',{target:mr(m)});assert.equal(m.armor,0);assert.equal(m.damage,2);spell(s,'spaccacorazze_della_giungla',{target:mr(m)});assert.equal(m.damage,3)});
test('Tutto per la Vittoria paga scarto immediatamente e dà Carica 6',()=>{const s=fresh();s.players[1].hand=['linfa_vitale'];cast(s,'tutto_per_la_vittoria',{discardId:'linfa_vitale',target:cp(1,champ(s).id)});assert.ok(s.players[1].grave.includes('linfa_vitale'));drain(s);assert.equal(E.pow(s,1,champ(s)),8);s.focus=1;game.act(s,1,{type:'attack',champId:champ(s).id,target:cp(2,champ(s,2).id)});assert.equal(E.pow(s,1,champ(s)),14);drain(s);assert.equal(E.pow(s,1,champ(s)),8)});
test('Doppio Colpo colpisce due nemici diversi e condivide frecce',()=>{const s=fresh(),a=mon(s),b=mon(s);cast(s,'doppio_colpo',{enemies:[mr(a),mr(b)]});const one=game.publicView(s,1).stack.at(-1),two=game.publicView(s,2).stack.at(-1);assert.equal(one.targetRefs.length,2);assert.deepEqual(one.targetRefs,two.targetRefs);drain(s);assert.equal(a.damage,2);assert.equal(b.damage,2)});
test('Doppio Colpo rifiuta bersaglio duplicato',()=>{const s=fresh(),m=mon(s);s.players[1].hand=['doppio_colpo'];assert.throws(()=>game.act(s,1,{type:'cast',cardId:'doppio_colpo',targets:{enemies:[mr(m),mr(m)]}}))});
test('Grido, Sangue e Carica Incendiaria: si sommano solo in attacco',()=>{const s=fresh();spell(s,'grido_di_guerra');spell(s,'sangue_bollente',{target:cp(1,champ(s).id)});spell(s,'carica_incendiaria',{target:cp(1,champ(s).id)});assert.equal(champ(s).charge,6);assert.equal(E.pow(s,1,champ(s)),8);s.focus=1;game.act(s,1,{type:'attack',champId:champ(s).id,target:cp(2,champ(s,2).id)});assert.equal(E.pow(s,1,champ(s)),14);assert.equal(E.pow(s,2,champ(s,2)),8);drain(s);end(s);assert.equal(champ(s).charge,undefined)});
test('Ritorsione può essere giocata normalmente',()=>{const s=fresh(),m=mon(s);m.tempPow=10;spell(s,'ritorsione_cremisi',{target:mr(m)});assert.equal(m.damage,4);assert.equal(s.pendingChoice,null)});
test('Ritorsione scartata offre scelta, paga e va in pila con bersaglio',()=>{const s=fresh(),m=mon(s);s.players[1].hand=['ritorsione_cremisi'];cast(s,'tutto_per_la_vittoria',{discardId:'ritorsione_cremisi',target:cp(1,champ(s).id)});assert.equal(s.pendingChoice.type,'batch3_discard');const before=s.players[1].souls.red;game.act(s,1,{type:'resolve_choice',targets:{target:mr(m)}});assert.equal(s.players[1].souls.red,before-1);assert.equal(s.stack.at(-1).cardId,'ritorsione_cremisi');assert.deepEqual(game.publicView(s,1).stack.at(-1).targetRefs,game.publicView(s,2).stack.at(-1).targetRefs);drain(s);assert.equal(s.board.monsters.length,0)});
test('Ritorsione: Passa ripristina priorità senza bloccare',()=>{const s=fresh();s.players[1].hand=['ritorsione_cremisi'];cast(s,'tutto_per_la_vittoria',{discardId:'ritorsione_cremisi',target:cp(1,champ(s).id)});game.act(s,1,{type:'resolve_choice',decline:true});assert.equal(s.pendingChoice,null);assert.equal(s.priority,2);drain(s)});
test('Erosione uccide dopo riduzione di una carta e non dopo bonus scaduto',()=>{const s=fresh(),m=mon(s);m.tempPow=4;spell(s,'erosione_polare',{target:mr(m)});spell(s,'vincolo_di_brina',{champion:cp(1,champ(s).id),enemy:mr(m)});assert.equal(s.board.monsters.length,0);const t=fresh(),b=mon(t);b.tempPow=4;spell(t,'erosione_polare',{target:mr(b)});end(t);assert.ok(t.board.monsters.some(x=>x.uid===b.uid))});
test('Erosione funziona anche con vecchie carte di riduzione',()=>{const s=fresh(),m=mon(s);spell(s,'erosione_polare',{target:mr(m)});spell(s,'flusso_gelido',{monsterUid:m.uid});assert.equal(s.board.monsters.length,0)});
test('Nuove magie rispettano Mantide',()=>{const s=fresh(),m=mon(s,'mantide_della_giungla');s.players[1].hand=['mandato_di_morte'];assert.throws(()=>game.act(s,1,{type:'cast',cardId:'mandato_di_morte',targets:{target:mr(m)}}))});
test('Rinascita non riattiva Minotauro, Balena o Elementale',()=>{for(const id of ['minotauro_infernale','balena_della_tempesta','elementale_della_brina']){const s=fresh(),m=mon(s,id);s.players[1].hand=['linfa_vitale'];spell(s,'rinascita',{target:mr(m)});spell(s,'mandato_di_morte',{target:mr(m)});assert.equal(s.pendingChoice,null,id);assert.equal(s.board.monsters[0].armor,0,id);assert.equal(champ(s).tempPow,0,id);assert.ok(s.players[1].hand.includes('linfa_vitale'),id)}});
test('Rinascita: Lascito originale in pila prima della resurrezione',()=>{const s=fresh(),m=mon(s,'custode_sepolcrale');spell(s,'rinascita',{target:mr(m)});cast(s,'mandato_di_morte',{target:mr(m)});pass(s);assert.equal(s.board.monsters.length,0);assert.ok(s.stack.some(x=>x.effectId==='batch3_revive'));assert.equal(s.stack.at(-1).effectId,'lascito_custode');pass(s);assert.equal(champ(s).tempPow,1);assert.equal(s.board.monsters.length,0);drain(s);assert.equal(s.board.monsters.length,1)});
test('Erosione riconosce anche Morsa, non Medusa',()=>{for(const id of ['morsa_dell_inverno']){const s=fresh(),m=mon(s);m.tempPow=4;spell(s,'erosione_polare',{target:mr(m)});spell(s,id,{target:mr(m)});assert.equal(s.board.monsters.length,0,id)}const s=fresh(),m=mon(s);m.tempPow=10;mon(s,'medusa_delle_maree');spell(s,'erosione_polare',{target:mr(m)});spell(s,'vincolo_di_brina',{champion:cp(1,champ(s).id),enemy:mr(m)});assert.ok(s.board.monsters.includes(m));assert.equal(m.tempPow,10);assert.equal(m.damage,2)});
test('Richiamo verde non rende permanente una Provocazione temporanea',()=>{const s=fresh(),m=mon(s);spell(s,'guardiano_delle_radici',{target:mr(m)});spell(s,'richiamo_del_branco_verde',{target:mr(m)});end(s);assert.equal(m.provocazione,false)});
test('Lascito Profanato del Mostro avversario è attivato dal lanciatore',()=>{const s=fresh(),m=mon(s,'custode_sepolcrale',2);spell(s,'lascito_profanato',{target:mr(m)});assert.equal(champ(s).tempPow,1);assert.equal(champ(s,2).tempPow,0);assert.ok(s.board.monsters.includes(m))});
test('Angelo paga Vincolo come costo aggiuntivo anche dal mazzo',()=>{const s=fresh(),m=mon(s);s.players[1].deck=['vincolo_di_brina'];spell(s,'angelo');game.act(s,1,{type:'resolve_choice',cardId:'vincolo_di_brina',targets:{champion:cp(1,champ(s).id),enemy:mr(m)}});assert.equal(champ(s).tapped,true);assert.equal(m.tempPow,0);drain(s);assert.equal(m.tempPow,-2)});
let failed=0;for(const [name,fn] of tests){try{fn();console.log('✓ '+name)}catch(e){failed++;console.error('✗ '+name+'\n'+String(e.stack).replace(/data:text\/javascript[^\n]+/g,'[engine]'))}}console.log(`${tests.length-failed}/${tests.length} passed`);process.exitCode=failed?1:0;
