import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
globalThis.fetch=async input=>new Response(await fs.readFile(new URL('../soulforge/'+String(input).split('/').pop().split('?')[0],import.meta.url),'utf8'));
const game=await import('../soulforge/game-v61-loader.ts');
const {engine61:E}=await import('../soulforge/game-v32-loader.ts?rev=souls-uncapped-v3');
const {cards,monsters}=await import('../soulforge/september-catalog.js');
const cp=(p,id)=>({type:'champion',player:p,champId:id});
const mt=m=>({type:'monster',uid:m.uid});
function fresh(){
 const deck={champions:['scarlet','torvald'],cards:Object.values(game.CARD_DEFS).filter(x=>['red','green'].includes(x.color)&&!x.tokenSupport).slice(0,18).map(x=>x.id),monsters:Object.values(game.MONSTER_DEFS).filter(x=>['red','green'].includes(x.color)).slice(0,12).map(x=>x.id)};
 const s=game.newState('A',deck);s.players['2']=game.newPlayer('B',deck);
 Object.assign(s,{status:'main',turn:3,focus:1,priority:null,stack:[],stackInitiator:null,combat:null,pendingChoice:null,triggerQueue:[],enterQueue:[],log:[],board:{monsters:[]}});
 for(const p of [1,2]){const q=s.players[p];Object.assign(q,{hand:[],grave:[],monsterGrave:[],selected:true,deckColors:['red','green','black','blue','orange'],souls:{red:100,green:100,black:100,blue:100,orange:100}});for(const c of q.champions)Object.assign(c,{basePow:4,hp:10,damage:0,wounds:0,armor:0,tempPow:0,tapped:false})}return s;
}
function mon(s,id,owner=1,extra={}){const m={uid:crypto.randomUUID(),cardId:id,owner,damage:0,tempPow:0,powMod:0,armor:0,...extra};s.board.monsters.push(m);return m}
const c=(s,p=1)=>s.players[p].champions[0];
const pass=s=>game.act(s,Number(s.priority),{type:'pass_priority'});
function cast(s,id,targets={},p=1){s.players[p].hand.push(id);game.act(s,p,{type:'cast',cardId:id,targets});}
function spell(s,id,targets={},p=1){cast(s,id,targets,p);pass(s)}
const tests=[];const test=(name,fn)=>tests.push([name,fn]);
test('18 Magie e 2 Mostri disponibili nelle definizioni',()=>{assert.equal(cards.length,18);assert.equal(monsters.length,2);for(const d of cards)assert.equal(game.CARD_DEFS[d.id].cost,d.cost);for(const d of monsters)assert.ok(game.STARTER_MONSTERS.includes(d.id))});
test('Pelle protegge dai danni di una nuova magia',()=>{const s=fresh();spell(s,'pelle_di_quercia_antica',{target:cp(1,c(s).id)});E.damageChampion(s,1,c(s).id,6,'test');assert.equal(c(s).wounds,0);assert.equal(c(s).damage,0)});
test('Pelle protegge anche da Galeone Fantasma',()=>{const s=fresh();spell(s,'pelle_di_quercia_antica',{target:cp(1,c(s).id)});s.focus=2;s.players[2].hand=[];s.players[2].deck=[];spell(s,'galeone_fantasma',{},2);assert.equal(c(s).wounds,0);assert.equal(c(s).damage,0)});
test('Ira colpisce fino a tre bersagli differenti e rifiuta duplicati',()=>{const s=fresh(),a=mon(s,'lucertola_fuoco'),b=mon(s,'lucertola_fuoco');s.players[1].hand.push('ira_del_sottobosco');assert.throws(()=>game.act(s,1,{type:'cast',cardId:'ira_del_sottobosco',targets:{monsterUids:[a.uid,a.uid]}}));spell(s,'ira_del_sottobosco',{monsterUids:[a.uid,b.uid]});assert.equal(s.board.monsters.length,0)});
test('Patto conserva istanza, HP 1, bonus e danni ed esclude bersagli Mostro',()=>{const s=fresh(),m=mon(s,'custode_sepolcrale',1,{damage:1,tempPow:2,powMod:1,armor:3});spell(s,'patto_della_foresta',{target:mt(m)});const x=s.players[1].champions.find(x=>x.monsterOrigin);assert.ok(x);assert.equal(x.hp,1);assert.equal(x.tapped,false);assert.equal(x.damage,1);assert.equal(x.armor,3);assert.equal(E.pow(s,1,x),5);assert.equal(s.board.monsters.length,0);s.focus=1;s.players[1].hand.push('scaglie_di_gelo');assert.throws(()=>game.act(s,1,{type:'cast',cardId:'scaglie_di_gelo',targets:{target:mt(m)}}))});
test('Patto rifiuta il Mostro proveniente dal mazzo avversario',()=>{const s=fresh(),m=mon(s,'lucertola_fuoco',2);s.players[1].hand.push('patto_della_foresta');assert.throws(()=>game.act(s,1,{type:'cast',cardId:'patto_della_foresta',targets:{target:mt(m)}}));assert.equal(s.board.monsters.length,1)});
test('Colpo al Cuore aggiunge una sola Ferita',()=>{const s=fresh();spell(s,'colpo_al_cuore',{target:cp(2,c(s,2).id)});E.wound(s,2,c(s,2),'test');assert.equal(c(s,2).wounds,2);E.wound(s,2,c(s,2),'test');assert.equal(c(s,2).wounds,3)});
test('Linfa cura danni e non Ferite',()=>{const s=fresh();c(s).damage=3;c(s).wounds=2;spell(s,'linfa_vitale',{target:cp(1,c(s).id)});assert.equal(c(s).damage,1);assert.equal(c(s).wounds,2)});
test('Furia della Selva apre priorità e mantiene il Mostro sul campo',()=>{const s=fresh();s.players[1].monsterDeck=['lucertola_fuoco'];spell(s,'furia_della_selva',{target:cp(2,c(s,2).id)});assert.equal(s.combat?.attacker?.type,'monster');assert.equal(s.priority,2);pass(s);pass(s);assert.equal(s.combat,null);assert.equal(s.board.monsters.length,1);assert.ok(c(s,2).damage>0)});
test('Furia del Ferito riattiva ripetutamente dopo danni non prevenuti',()=>{const s=fresh();spell(s,'furia_del_ferito',{target:cp(1,c(s).id)});c(s).tapped=true;E.damageChampion(s,1,c(s).id,1,'test');assert.equal(c(s).tapped,false);c(s).tapped=true;E.damageChampion(s,1,c(s).id,1,'test');assert.equal(c(s).tapped,false)});
test('Sigillo non concede anime se il suo stesso danno uccide',()=>{const s=fresh(),m=mon(s,'lucertola_fuoco',1,{damage:2});const before=s.players[1].souls.red;spell(s,'sigillo_dell_oblio',{target:mt(m)});assert.equal(s.board.monsters.length,0);assert.equal(s.players[1].souls.red,before)});
test('Scaglie ed Egida forniscono armatura al bersaglio corretto',()=>{const s=fresh(),m=mon(s,'lucertola_fuoco');spell(s,'scaglie_di_gelo',{target:mt(m)});assert.equal(m.armor,3);s.focus=1;spell(s,'egida_d_acciaio',{target:cp(2,c(s,2).id)});assert.equal(c(s,2).armor,2)});
test('Fortezza raddoppia l’armatura attuale',()=>{const s=fresh();c(s).armor=3;spell(s,'fortezza_di_cristallo',{target:cp(1,c(s).id)});assert.equal(c(s).armor,6)});
test('Stasi azzera POW e dà 10 Armatura, Respiro infligge Ferita',()=>{const s=fresh();spell(s,'stasi_del_leviatano',{target:cp(1,c(s).id)});assert.equal(E.pow(s,1,c(s)),0);assert.equal(c(s).armor,10);s.focus=2;spell(s,'respiro_dell_inverno',{target:cp(1,c(s).id)},2);assert.equal(c(s).wounds,1)});
test('Riflesso usa l’Armatura attuale del Campione',()=>{const s=fresh();c(s).armor=3;spell(s,'riflesso_polare',{champion:cp(1,c(s).id),enemy:cp(2,c(s,2).id)});assert.equal(c(s,2).damage,3)});
test('Morsa imposta POW a 2',()=>{const s=fresh();spell(s,'morsa_dell_inverno',{target:cp(2,c(s,2).id)});assert.equal(E.pow(s,2,c(s,2)),2)});
test('Distruttore annulla una Magia senza risolverla',()=>{const s=fresh();cast(s,'linfa_vitale',{target:cp(1,c(s).id)});const uid=s.stack[0].uid;cast(s,'distruttore_dell_oscurita',{stackUid:uid},2);pass(s);assert.equal(s.stack.length,0);assert.ok(s.players[1].grave.includes('linfa_vitale'))});
test('Stendardi concede Contrattacco e non attacco extra',()=>{const s=fresh();spell(s,'stendardi_della_legione_dorata',{target:cp(1,c(s).id)});s.focus=2;game.act(s,2,{type:'attack',champId:c(s,2).id,target:cp(1,c(s).id)});pass(s);pass(s);assert.equal(c(s).wounds,1);assert.equal(c(s,2).wounds,1)});
test('Carica solo per Supporti attaccanti, rimosso a fine combattimento',()=>{const s=fresh();const x={...c(s),id:'support-test',basePow:2,supportChampion:true,hp:1};s.players[1].champions.push(x);spell(s,'carica_degli_impavidi');assert.equal(E.pow(s,1,x),2);s.focus=1;game.act(s,1,{type:'attack',champId:x.id,target:cp(2,c(s,2).id)});assert.equal(E.pow(s,1,x),3);pass(s);pass(s);assert.equal(E.pow(s,1,x),2);assert.equal(c(s,2).damage,3)});
test('Vampiro uccide a destra senza anime',()=>{const s=fresh(),v=mon(s,'vampiro'),victim=mon(s,'lucertola_fuoco');s.enterQueue=[v.uid];s.stack=[{uid:'noop',kind:'effect',actor:1,effectId:'noop',targets:{}}];s.priority=2;const before=s.players[1].souls.red;pass(s);assert.ok(!s.board.monsters.includes(victim));assert.equal(s.players[1].souls.red,before)});
test('Abominio potenzia gli altri Mostri quando uno muore',()=>{const s=fresh(),a=mon(s,'abominio_ricucito'),b=mon(s,'custode_sepolcrale'),dead=mon(s,'lucertola_fuoco');E.kill(s,1,dead,'test');assert.equal(a.tempPow,0);assert.equal(b.tempPow,1)});
test('Bersagli identici per entrambi, nessuna scelta pubblica prima del lancio',()=>{const s=fresh(),target=cp(1,c(s).id);assert.equal(game.publicView(s,2).stack.length,0);cast(s,'linfa_vitale',{target});assert.deepEqual(game.publicView(s,1).stack[0].targetRefs,[target]);assert.deepEqual(game.publicView(s,2).stack[0].targetRefs,[target])});
test('Patto non genera anime o Lasciti durante il trasferimento',()=>{const s=fresh(),m=mon(s,'scorpione_delle_ceneri');const before=s.players[1].souls.red;spell(s,'patto_della_foresta',{target:mt(m)});assert.equal(s.players[1].souls.red,before);assert.equal(s.pendingChoice,null);assert.equal(s.stack.length,0)});
test('Il Lascito del Supporto trasformato spetta al suo controllore',()=>{const s=fresh(),m=mon(s,'marionetta_maledetta');spell(s,'patto_della_foresta',{target:mt(m)});const x=s.players[1].champions.find(x=>x.monsterOrigin);s.players[2].grave=['linfa_vitale'];s.focus=2;c(s,2).armor=9;const before={...s.players[2].souls};spell(s,'riflesso_polare',{champion:cp(2,c(s,2).id),enemy:cp(1,x.id)},2);assert.ok(s.players[1].monsterGrave.includes('marionetta_maledetta'));assert.ok(!s.players[1].grave.includes('marionetta_maledetta'));assert.equal(s.pendingChoice?.player,1);assert.equal(s.pendingChoice?.trigger?.effectId,'v60_marionetta_lascito');assert.deepEqual(s.players[2].souls,{...before,blue:before.blue-1})});
test('Patto mantiene l’aura del Gorilla trasformato',()=>{const s=fresh(),m=mon(s,'gorilla_della_giungla');spell(s,'patto_della_foresta',{target:mt(m)});const x=s.players[1].champions.find(x=>x.monsterOrigin);s.focus=2;c(s,2).armor=9;spell(s,'riflesso_polare',{champion:cp(2,c(s,2).id),enemy:cp(1,x.id)},2);assert.equal(x.defeated,false);assert.equal(x.damage,0)});
test('La trasformazione mantiene l’aura del Lupo delle Radici',()=>{const s=fresh(),wolf=mon(s,'lupo_delle_radici'),m=mon(s,'lucertola_fuoco');const before=E.monsterPow(s,m);spell(s,'patto_della_foresta',{target:mt(wolf)});assert.equal(E.monsterPow(s,m),before)});
test('Tutta l’armatura e Carica scadono a fine turno',()=>{const s=fresh();c(s).armor=7;c(s).charge=2;c(s).chargeTurn=s.turn;const m=mon(s,'lucertola_fuoco',1,{armor:4});game.act(s,1,{type:'pass'});game.act(s,2,{type:'pass'});assert.equal(s.turn,4);assert.equal(c(s).armor,0);assert.equal(m.armor,0);assert.equal(c(s).charge,undefined)});
test('Carica non si applica al Supporto in difesa',()=>{const s=fresh(),x={...c(s),id:'support-def',basePow:2,hp:5,supportChampion:true};s.players[1].champions.push(x);spell(s,'carica_degli_impavidi');s.focus=2;game.act(s,2,{type:'attack',champId:c(s,2).id,target:cp(1,x.id)});assert.equal(E.pow(s,1,x),2)});
test('Sigillo continua a negare anime quando uccide una vecchia carta',()=>{const s=fresh(),m=mon(s,'lucertola_fuoco');spell(s,'sigillo_dell_oblio',{target:mt(m)});s.focus=1;const before=s.players[1].souls.red;spell(s,'colpo_di_cannone',{enemy:mt(m)});assert.equal(s.board.monsters.length,0);assert.equal(s.players[1].souls.red,before-2)});
test('La morte dell’attaccante annulla il combattimento di Furia',()=>{const s=fresh();s.players[1].monsterDeck=['lucertola_fuoco'];spell(s,'furia_della_selva',{target:cp(2,c(s,2).id)});E.kill(s,2,s.board.monsters[0],'test');pass(s);pass(s);assert.equal(s.combat,null);assert.equal(c(s,2).damage,0)});
test('Stendardi contrattacca anche contro Furia della Selva',()=>{const s=fresh();spell(s,'stendardi_della_legione_dorata',{target:cp(1,c(s).id)});s.focus=2;s.players[2].monsterDeck=['lucertola_fuoco'];spell(s,'furia_della_selva',{target:cp(1,c(s).id)},2);pass(s);pass(s);assert.equal(s.board.monsters.length,0)});
test('Vampiro assegna il Lascito di Sciamano senza anime',()=>{const s=fresh(),v=mon(s,'vampiro'),victim=mon(s,'sciamano_del_sole',2);s.enterQueue=[v.uid];s.stack=[{uid:'noop',kind:'effect',actor:1,effectId:'noop',targets:{}}];s.priority=2;const souls={...s.players[1].souls};pass(s);assert.ok(!s.board.monsters.includes(victim));assert.deepEqual(s.players[1].souls,souls);assert.ok([...s.stack,...s.triggerQueue,...(s._orangeTriggers||[])].some(x=>x.effectId==='lascito_sciamano'&&Number(x.actor)===1));});
test('Abominio reagisce anche alla vecchia Offerta Maligna',()=>{const s=fresh(),a=mon(s,'abominio_ricucito'),b=mon(s,'lucertola_fuoco'),d=mon(s,'lucertola_fuoco',2),survivor=mon(s,'custode_sepolcrale');spell(s,'offerta_maligna',{monsterUid:b.uid});game.act(s,2,{type:'resolve_choice',monsterUid:d.uid});assert.equal(survivor.tempPow,2);assert.equal(a.tempPow,0)});
let failed=0;for(const [name,fn] of tests){try{fn();console.log('✓ '+name)}catch(e){failed++;console.error('✗ '+name+'\n'+e.stack)}}console.log(`${tests.length-failed}/${tests.length} passed`);process.exitCode=failed?1:0;
