import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {cards,monsters} from '../soulforge/new20-catalog.js';
const loader=await fs.readFile(new URL('../soulforge/blue-v22-loader.js',import.meta.url),'utf8');
let source=(await Promise.all([1,2,3,4].map(i=>fs.readFile(new URL(`../soulforge/blue-v22.p0${i}.txt`,import.meta.url),'utf8')))).join('');
const edits=loader.slice(loader.indexOf("if(!js.includes('const artUrl"),loader.indexOf(' (0,eval)(js);'));
source=new Function('js',edits+'return js')(source);
new Function(source);
const prefix=source.slice(source.indexOf('const OLD_BASE='),source.indexOf('const labelColor='));
const window={};
const renderArt=new Function('window','esc',prefix+'window.sfArtUrl21=legacyArtUrl21;return {artUrl,artImg};')(window,s=>String(s));
const legacy=window.sfArtUrl21;
const definitions=Object.fromEntries([...cards,...monsters].map(x=>[x.id,x]));
window.sfArtUrl21=id=>definitions[id]?'https://example.test/'+definitions[id].art:legacy(id);
for(const d of [...cards,...monsters])assert.ok(renderArt.artImg(d.id).includes(d.art),d.id);
assert.ok(renderArt.artImg('kael').includes('kael.webp'));
assert.equal(renderArt.artImg('missing'),'');
const wrapper=loader.slice(loader.indexOf(' const previousSelect=renderSelect;'),loader.indexOf(" const colors=['red'"));
const baseSelect=()=>'<div>Scegli 6 carte</div>';
const opponent={name:'B',champions:[{id:'kael',name:'Kael'},{id:'scarlet',name:'Scarlet'},{id:'servo',supportChampion:true}]};
const select=new Function('renderSelect','playerState','otherP','esc','champHtml',wrapper+'return renderSelect')(baseSelect,()=>opponent,()=>2,s=>String(s),c=>`<img alt="${c.name}">`);
const html=select();assert.ok(html.indexOf('Campioni avversari')<html.indexOf('Scegli 6 carte'));assert.ok(html.includes('alt="Kael"')&&html.includes('alt="Scarlet"'));assert.ok(!html.includes('servo'));
console.log('All 20 in-game artwork URLs, legacy fallback and opponent preview before selection verified.');
